#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
# 
# Add this file to .git/hooks
# 
# Runs gofmt on the code and stops commit if files were affected.
# 
gofmt -w -l */*.go */*/*.go | grep \.go && (echo formatted your Go code, please commit again; exit 1)

astyle --indent=tab cuda/*.cu | grep Formatted && (echo formatted your CUDA code, please commit again; exit 1)

exit 0
