#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
# 
# Add this file to .git/hooks
# 
# Runs gofmt on the code and stops commit if files were affected.
# 
gofmt -w -l *.go */*.go */*/*.go | grep \.go || exit 0
echo formatted your code, please commit again
exit 1
