#! /bin/bash
out=$(echo $1 | md5sum | cut -c 1-16 -)
dir=formulae
echo $dir/$out
if [ ! -f $dir/$out.png ]; then
	echo "\documentclass{article} \begin{document} \pagestyle{empty} \[" $1 "\]\end{document}" > $out.tex
	(
		pdflatex $out.tex 
		pdfcrop $out.pdf $out.pdf.out
		mv $out.pdf.out $out.pdf
		convert -density 120 $out.pdf $dir/$out.png
		rm $out.pdf
		rm $out.tex
		rm $out.aux
		rm $out.log
	) >> /dev/null 2>/dev/null
fi
