package kernel

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"unsafe"
)

var dmi_code cu.Function

type dmi_args struct {
	arg_Hx unsafe.Pointer
	arg_Hy unsafe.Pointer
	arg_Hz unsafe.Pointer
	arg_mx unsafe.Pointer
	arg_my unsafe.Pointer
	arg_mz unsafe.Pointer
	arg_cx float32
	arg_cy float32
	arg_cz float32
	arg_dx float32
	arg_dy float32
	arg_dz float32
	arg_N0 int
	arg_N1 int
	arg_N2 int
	argptr [15]unsafe.Pointer
}

// Wrapper for dmi CUDA kernel, asynchronous.
func K_dmi_async(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, cx float32, cy float32, cz float32, dx float32, dy float32, dz float32, N0 int, N1 int, N2 int, gridDim, blockDim cu.Dim3, str cu.Stream) {
	if dmi_code == 0 {
		dmi_code = cu.ModuleLoadData(dmi_ptx).GetFunction("dmi")
	}

	var a dmi_args

	a.arg_Hx = Hx
	a.argptr[0] = unsafe.Pointer(&a.arg_Hx)
	a.arg_Hy = Hy
	a.argptr[1] = unsafe.Pointer(&a.arg_Hy)
	a.arg_Hz = Hz
	a.argptr[2] = unsafe.Pointer(&a.arg_Hz)
	a.arg_mx = mx
	a.argptr[3] = unsafe.Pointer(&a.arg_mx)
	a.arg_my = my
	a.argptr[4] = unsafe.Pointer(&a.arg_my)
	a.arg_mz = mz
	a.argptr[5] = unsafe.Pointer(&a.arg_mz)
	a.arg_cx = cx
	a.argptr[6] = unsafe.Pointer(&a.arg_cx)
	a.arg_cy = cy
	a.argptr[7] = unsafe.Pointer(&a.arg_cy)
	a.arg_cz = cz
	a.argptr[8] = unsafe.Pointer(&a.arg_cz)
	a.arg_dx = dx
	a.argptr[9] = unsafe.Pointer(&a.arg_dx)
	a.arg_dy = dy
	a.argptr[10] = unsafe.Pointer(&a.arg_dy)
	a.arg_dz = dz
	a.argptr[11] = unsafe.Pointer(&a.arg_dz)
	a.arg_N0 = N0
	a.argptr[12] = unsafe.Pointer(&a.arg_N0)
	a.arg_N1 = N1
	a.argptr[13] = unsafe.Pointer(&a.arg_N1)
	a.arg_N2 = N2
	a.argptr[14] = unsafe.Pointer(&a.arg_N2)

	args := a.argptr[:]
	cu.LaunchKernel(dmi_code, gridDim.X, gridDim.Y, gridDim.Z, blockDim.X, blockDim.Y, blockDim.Z, 0, str, args)
}

// Wrapper for dmi CUDA kernel, synchronized.
func K_dmi(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, cx float32, cy float32, cz float32, dx float32, dy float32, dz float32, N0 int, N1 int, N2 int, gridDim, blockDim cu.Dim3) {
	str := Stream()
	K_dmi_async(Hx, Hy, Hz, mx, my, mz, cx, cy, cz, dx, dy, dz, N0, N1, N2, gridDim, blockDim, str)
	SyncAndRecycle(str)
}

const dmi_ptx = `
.version 3.1
.target sm_30
.address_size 64


.visible .entry dmi(
	.param .u64 dmi_param_0,
	.param .u64 dmi_param_1,
	.param .u64 dmi_param_2,
	.param .u64 dmi_param_3,
	.param .u64 dmi_param_4,
	.param .u64 dmi_param_5,
	.param .f32 dmi_param_6,
	.param .f32 dmi_param_7,
	.param .f32 dmi_param_8,
	.param .f32 dmi_param_9,
	.param .f32 dmi_param_10,
	.param .f32 dmi_param_11,
	.param .u32 dmi_param_12,
	.param .u32 dmi_param_13,
	.param .u32 dmi_param_14
)
{
	.reg .pred 	%p<10>;
	.reg .s32 	%r<129>;
	.reg .f32 	%f<37>;
	.reg .s64 	%rd<46>;


	ld.param.u64 	%rd4, [dmi_param_0];
	ld.param.u64 	%rd5, [dmi_param_1];
	ld.param.u64 	%rd6, [dmi_param_2];
	ld.param.u64 	%rd7, [dmi_param_3];
	ld.param.u64 	%rd8, [dmi_param_4];
	ld.param.u64 	%rd9, [dmi_param_5];
	ld.param.f32 	%f1, [dmi_param_6];
	ld.param.f32 	%f2, [dmi_param_7];
	ld.param.f32 	%f3, [dmi_param_8];
	ld.param.f32 	%f4, [dmi_param_9];
	ld.param.f32 	%f5, [dmi_param_10];
	ld.param.f32 	%f6, [dmi_param_11];
	ld.param.u32 	%r14, [dmi_param_12];
	ld.param.u32 	%r15, [dmi_param_13];
	ld.param.u32 	%r16, [dmi_param_14];
	.loc 2 17 1
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r17, %ntid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r3, %r17, %r1, %r2;
	.loc 2 18 1
	mov.u32 	%r18, %ntid.y;
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %tid.y;
	mad.lo.s32 	%r4, %r18, %r19, %r20;
	.loc 2 20 1
	setp.lt.s32 	%p1, %r4, %r16;
	setp.lt.s32 	%p2, %r3, %r15;
	and.pred  	%p3, %p2, %p1;
	.loc 2 24 1
	setp.gt.s32 	%p4, %r14, 0;
	.loc 2 20 1
	and.pred  	%p5, %p3, %p4;
	@!%p5 bra 	BB0_9;
	bra.uni 	BB0_1;

BB0_1:
	.loc 2 32 1
	add.s32 	%r5, %r14, -1;
	add.s32 	%r6, %r15, -1;
	.loc 2 24 1
	mad.lo.s32 	%r127, %r16, %r3, %r4;
	mul.lo.s32 	%r8, %r16, %r15;
	mov.u32 	%r21, 0;
	cvta.to.global.u64 	%rd10, %rd4;
	cvta.to.global.u64 	%rd12, %rd5;
	cvta.to.global.u64 	%rd43, %rd6;
	mov.u32 	%r128, %r21;

BB0_2:
	.loc 2 27 1
	mov.u32 	%r10, %r128;
	cvt.s64.s32 	%rd1, %r127;
	mul.wide.s32 	%rd11, %r127, 4;
	add.s64 	%rd2, %rd10, %rd11;
	.loc 2 28 1
	add.s64 	%rd3, %rd12, %rd11;
	st.global.u32 	[%rd3], %r21;
	.loc 2 29 1
	st.global.u32 	[%rd2], %r21;
	.loc 2 31 1
	setp.eq.f32 	%p6, %f4, 0f00000000;
	@%p6 bra 	BB0_4;

	mov.u32 	%r31, 0;
	.loc 3 238 5
	max.s32 	%r32, %r10, %r31;
	.loc 3 210 5
	min.s32 	%r33, %r32, %r5;
	.loc 2 32 1
	add.s32 	%r34, %r3, 1;
	.loc 3 238 5
	max.s32 	%r35, %r34, %r31;
	.loc 3 210 5
	min.s32 	%r36, %r35, %r6;
	.loc 2 32 1
	mad.lo.s32 	%r37, %r33, %r15, %r36;
	add.s32 	%r38, %r16, -1;
	.loc 3 238 5
	max.s32 	%r39, %r4, %r31;
	.loc 3 210 5
	min.s32 	%r40, %r39, %r38;
	.loc 2 32 1
	mad.lo.s32 	%r41, %r37, %r16, %r40;
	cvta.to.global.u64 	%rd13, %rd9;
	.loc 2 32 1
	mul.wide.s32 	%rd14, %r41, 4;
	add.s64 	%rd15, %rd13, %rd14;
	add.s32 	%r42, %r3, -1;
	.loc 3 238 5
	max.s32 	%r43, %r42, %r31;
	.loc 3 210 5
	min.s32 	%r44, %r43, %r6;
	.loc 2 32 1
	mad.lo.s32 	%r45, %r33, %r15, %r44;
	add.s32 	%r46, %r4, -1;
	.loc 3 238 5
	max.s32 	%r47, %r46, %r31;
	.loc 3 210 5
	min.s32 	%r48, %r47, %r38;
	.loc 2 32 1
	mad.lo.s32 	%r49, %r45, %r16, %r48;
	mul.wide.s32 	%rd16, %r49, 4;
	add.s64 	%rd17, %rd13, %rd16;
	ld.global.f32 	%f7, [%rd17];
	ld.global.f32 	%f8, [%rd15];
	sub.f32 	%f9, %f8, %f7;
	.loc 4 2399 3
	div.rn.f32 	%f10, %f9, %f2;
	.loc 3 238 5
	max.s32 	%r52, %r3, %r31;
	.loc 3 210 5
	min.s32 	%r53, %r52, %r6;
	.loc 2 33 1
	mad.lo.s32 	%r54, %r33, %r15, %r53;
	add.s32 	%r55, %r4, 1;
	.loc 3 238 5
	max.s32 	%r56, %r55, %r31;
	.loc 3 210 5
	min.s32 	%r57, %r56, %r38;
	.loc 2 33 1
	mad.lo.s32 	%r58, %r54, %r16, %r57;
	cvta.to.global.u64 	%rd18, %rd8;
	.loc 2 33 1
	mul.wide.s32 	%rd19, %r58, 4;
	add.s64 	%rd20, %rd18, %rd19;
	mad.lo.s32 	%r59, %r54, %r16, %r40;
	mul.wide.s32 	%rd21, %r59, 4;
	add.s64 	%rd22, %rd18, %rd21;
	ld.global.f32 	%f11, [%rd22];
	ld.global.f32 	%f12, [%rd20];
	sub.f32 	%f13, %f12, %f11;
	.loc 4 2399 3
	div.rn.f32 	%f14, %f13, %f3;
	.loc 2 34 1
	sub.f32 	%f15, %f10, %f14;
	mul.f32 	%f16, %f15, %f4;
	st.global.f32 	[%rd2], %f16;

BB0_4:
	.loc 2 37 1
	setp.eq.f32 	%p7, %f5, 0f00000000;
	@%p7 bra 	BB0_6;

	.loc 2 38 1
	add.s32 	%r63, %r10, 1;
	mov.u32 	%r64, 0;
	.loc 3 238 5
	max.s32 	%r65, %r63, %r64;
	.loc 3 210 5
	min.s32 	%r66, %r65, %r5;
	.loc 3 238 5
	max.s32 	%r67, %r3, %r64;
	.loc 3 210 5
	min.s32 	%r68, %r67, %r6;
	.loc 2 38 1
	mad.lo.s32 	%r69, %r66, %r15, %r68;
	.loc 2 32 1
	add.s32 	%r70, %r16, -1;
	.loc 3 238 5
	max.s32 	%r71, %r4, %r64;
	.loc 3 210 5
	min.s32 	%r72, %r71, %r70;
	.loc 2 38 1
	mad.lo.s32 	%r73, %r69, %r16, %r72;
	cvta.to.global.u64 	%rd23, %rd9;
	.loc 2 38 1
	mul.wide.s32 	%rd24, %r73, 4;
	add.s64 	%rd25, %rd23, %rd24;
	add.s32 	%r74, %r10, -1;
	.loc 3 238 5
	max.s32 	%r75, %r74, %r64;
	.loc 3 210 5
	min.s32 	%r76, %r75, %r5;
	.loc 2 38 1
	mad.lo.s32 	%r77, %r76, %r15, %r68;
	mad.lo.s32 	%r78, %r77, %r16, %r72;
	mul.wide.s32 	%rd26, %r78, 4;
	add.s64 	%rd27, %rd23, %rd26;
	ld.global.f32 	%f17, [%rd27];
	ld.global.f32 	%f18, [%rd25];
	sub.f32 	%f19, %f18, %f17;
	.loc 4 2399 3
	div.rn.f32 	%f20, %f19, %f1;
	.loc 3 238 5
	max.s32 	%r81, %r10, %r64;
	.loc 3 210 5
	min.s32 	%r82, %r81, %r5;
	.loc 2 39 1
	mad.lo.s32 	%r83, %r82, %r15, %r68;
	.loc 2 33 1
	add.s32 	%r84, %r4, 1;
	.loc 3 238 5
	max.s32 	%r85, %r84, %r64;
	.loc 3 210 5
	min.s32 	%r86, %r85, %r70;
	.loc 2 39 1
	mad.lo.s32 	%r87, %r83, %r16, %r86;
	cvta.to.global.u64 	%rd28, %rd7;
	.loc 2 39 1
	mul.wide.s32 	%rd29, %r87, 4;
	add.s64 	%rd30, %rd28, %rd29;
	mad.lo.s32 	%r88, %r83, %r16, %r72;
	mul.wide.s32 	%rd31, %r88, 4;
	add.s64 	%rd32, %rd28, %rd31;
	ld.global.f32 	%f21, [%rd32];
	ld.global.f32 	%f22, [%rd30];
	sub.f32 	%f23, %f22, %f21;
	.loc 4 2399 3
	div.rn.f32 	%f24, %f23, %f3;
	.loc 2 40 1
	sub.f32 	%f25, %f24, %f20;
	mul.f32 	%f26, %f25, %f4;
	st.global.f32 	[%rd3], %f26;

BB0_6:
	.loc 2 44 1
	add.s32 	%r11, %r10, 1;
	.loc 2 43 1
	setp.eq.f32 	%p8, %f6, 0f00000000;
	@%p8 bra 	BB0_8;

	mov.u32 	%r92, 0;
	.loc 3 238 5
	max.s32 	%r93, %r11, %r92;
	.loc 3 210 5
	min.s32 	%r94, %r93, %r5;
	.loc 3 238 5
	max.s32 	%r95, %r3, %r92;
	.loc 3 210 5
	min.s32 	%r96, %r95, %r6;
	.loc 2 44 1
	mad.lo.s32 	%r97, %r94, %r15, %r96;
	.loc 2 32 1
	add.s32 	%r98, %r16, -1;
	.loc 3 238 5
	max.s32 	%r99, %r4, %r92;
	.loc 3 210 5
	min.s32 	%r100, %r99, %r98;
	.loc 2 44 1
	mad.lo.s32 	%r101, %r97, %r16, %r100;
	cvta.to.global.u64 	%rd33, %rd8;
	.loc 2 44 1
	mul.wide.s32 	%rd34, %r101, 4;
	add.s64 	%rd35, %rd33, %rd34;
	add.s32 	%r102, %r10, -1;
	.loc 3 238 5
	max.s32 	%r103, %r102, %r92;
	.loc 3 210 5
	min.s32 	%r104, %r103, %r5;
	.loc 2 44 1
	mad.lo.s32 	%r105, %r104, %r15, %r96;
	mad.lo.s32 	%r106, %r105, %r16, %r100;
	mul.wide.s32 	%rd36, %r106, 4;
	add.s64 	%rd37, %rd33, %rd36;
	ld.global.f32 	%f27, [%rd37];
	ld.global.f32 	%f28, [%rd35];
	sub.f32 	%f29, %f28, %f27;
	.loc 4 2399 3
	div.rn.f32 	%f30, %f29, %f1;
	.loc 3 238 5
	max.s32 	%r109, %r10, %r92;
	.loc 3 210 5
	min.s32 	%r110, %r109, %r5;
	.loc 2 32 1
	add.s32 	%r111, %r3, 1;
	.loc 3 238 5
	max.s32 	%r112, %r111, %r92;
	.loc 3 210 5
	min.s32 	%r113, %r112, %r6;
	.loc 2 45 1
	mad.lo.s32 	%r114, %r110, %r15, %r113;
	mad.lo.s32 	%r115, %r114, %r16, %r100;
	cvta.to.global.u64 	%rd38, %rd7;
	.loc 2 45 1
	mul.wide.s32 	%rd39, %r115, 4;
	add.s64 	%rd40, %rd38, %rd39;
	.loc 2 32 1
	add.s32 	%r116, %r3, -1;
	.loc 3 238 5
	max.s32 	%r117, %r116, %r92;
	.loc 3 210 5
	min.s32 	%r118, %r117, %r6;
	.loc 2 45 1
	mad.lo.s32 	%r119, %r110, %r15, %r118;
	.loc 2 32 1
	add.s32 	%r120, %r4, -1;
	.loc 3 238 5
	max.s32 	%r121, %r120, %r92;
	.loc 3 210 5
	min.s32 	%r122, %r121, %r98;
	.loc 2 45 1
	mad.lo.s32 	%r123, %r119, %r16, %r122;
	mul.wide.s32 	%rd41, %r123, 4;
	add.s64 	%rd42, %rd38, %rd41;
	ld.global.f32 	%f31, [%rd42];
	ld.global.f32 	%f32, [%rd40];
	sub.f32 	%f33, %f32, %f31;
	.loc 4 2399 3
	div.rn.f32 	%f34, %f33, %f2;
	.loc 2 46 1
	sub.f32 	%f35, %f30, %f34;
	mul.f32 	%f36, %f35, %f4;
	shl.b64 	%rd44, %rd1, 2;
	add.s64 	%rd45, %rd43, %rd44;
	st.global.f32 	[%rd45], %f36;

BB0_8:
	.loc 2 24 1
	add.s32 	%r127, %r127, %r8;
	setp.lt.s32 	%p9, %r11, %r14;
	mov.u32 	%r128, %r11;
	@%p9 bra 	BB0_2;

BB0_9:
	.loc 2 49 2
	ret;
}


`
