#! /bin/bash
# wrapper for "go run" using gccgo with flags for speed.
echo go run -compiler=gccgo -gccgoflags '-static-libgcc -O4 -Ofast -march=native' $@
go run -compiler=gccgo -gccgoflags '-static-libgcc -O4 -Ofast -march=native' $@
