package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"unsafe"
)

var copypadmul_code cu.Function

type copypadmul_args struct {
	arg_dst     unsafe.Pointer
	arg_Dx      int
	arg_Dy      int
	arg_Dz      int
	arg_src     unsafe.Pointer
	arg_vol     unsafe.Pointer
	arg_Sx      int
	arg_Sy      int
	arg_Sz      int
	arg_BsatLUT unsafe.Pointer
	arg_regions unsafe.Pointer
	argptr      [11]unsafe.Pointer
}

// Wrapper for copypadmul CUDA kernel, asynchronous.
func k_copypadmul_async(dst unsafe.Pointer, Dx int, Dy int, Dz int, src unsafe.Pointer, vol unsafe.Pointer, Sx int, Sy int, Sz int, BsatLUT unsafe.Pointer, regions unsafe.Pointer, cfg *config, str cu.Stream) {
	if synchronous { // debug
		Sync()
	}

	if copypadmul_code == 0 {
		copypadmul_code = fatbinLoad(copypadmul_map, "copypadmul")
	}

	var _a_ copypadmul_args

	_a_.arg_dst = dst
	_a_.argptr[0] = unsafe.Pointer(&_a_.arg_dst)
	_a_.arg_Dx = Dx
	_a_.argptr[1] = unsafe.Pointer(&_a_.arg_Dx)
	_a_.arg_Dy = Dy
	_a_.argptr[2] = unsafe.Pointer(&_a_.arg_Dy)
	_a_.arg_Dz = Dz
	_a_.argptr[3] = unsafe.Pointer(&_a_.arg_Dz)
	_a_.arg_src = src
	_a_.argptr[4] = unsafe.Pointer(&_a_.arg_src)
	_a_.arg_vol = vol
	_a_.argptr[5] = unsafe.Pointer(&_a_.arg_vol)
	_a_.arg_Sx = Sx
	_a_.argptr[6] = unsafe.Pointer(&_a_.arg_Sx)
	_a_.arg_Sy = Sy
	_a_.argptr[7] = unsafe.Pointer(&_a_.arg_Sy)
	_a_.arg_Sz = Sz
	_a_.argptr[8] = unsafe.Pointer(&_a_.arg_Sz)
	_a_.arg_BsatLUT = BsatLUT
	_a_.argptr[9] = unsafe.Pointer(&_a_.arg_BsatLUT)
	_a_.arg_regions = regions
	_a_.argptr[10] = unsafe.Pointer(&_a_.arg_regions)

	args := _a_.argptr[:]
	cu.LaunchKernel(copypadmul_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, str, args)

	if synchronous { // debug
		Sync()
	}
}

// Wrapper for copypadmul CUDA kernel, synchronized.
func k_copypadmul_sync(dst unsafe.Pointer, Dx int, Dy int, Dz int, src unsafe.Pointer, vol unsafe.Pointer, Sx int, Sy int, Sz int, BsatLUT unsafe.Pointer, regions unsafe.Pointer, cfg *config) {
	Sync()
	k_copypadmul_async(dst, Dx, Dy, Dz, src, vol, Sx, Sy, Sz, BsatLUT, regions, cfg, stream0)
	Sync()
}

var copypadmul_map = map[int]string{0: "",
	20: copypadmul_ptx_20,
	30: copypadmul_ptx_30,
	35: copypadmul_ptx_35}

const (
	copypadmul_ptx_20 = `
.version 3.2
.target sm_20
.address_size 64


.visible .entry copypadmul(
	.param .u64 copypadmul_param_0,
	.param .u32 copypadmul_param_1,
	.param .u32 copypadmul_param_2,
	.param .u32 copypadmul_param_3,
	.param .u64 copypadmul_param_4,
	.param .u64 copypadmul_param_5,
	.param .u32 copypadmul_param_6,
	.param .u32 copypadmul_param_7,
	.param .u32 copypadmul_param_8,
	.param .u64 copypadmul_param_9,
	.param .u64 copypadmul_param_10
)
{
	.reg .pred 	%p<7>;
	.reg .s32 	%r<22>;
	.reg .f32 	%f<9>;
	.reg .s64 	%rd<22>;


	ld.param.u64 	%rd7, [copypadmul_param_0];
	ld.param.u32 	%r5, [copypadmul_param_1];
	ld.param.u32 	%r6, [copypadmul_param_2];
	ld.param.u64 	%rd8, [copypadmul_param_4];
	ld.param.u64 	%rd6, [copypadmul_param_5];
	ld.param.u32 	%r7, [copypadmul_param_6];
	ld.param.u32 	%r8, [copypadmul_param_7];
	ld.param.u32 	%r9, [copypadmul_param_8];
	ld.param.u64 	%rd9, [copypadmul_param_9];
	ld.param.u64 	%rd10, [copypadmul_param_10];
	cvta.to.global.u64 	%rd1, %rd7;
	cvta.to.global.u64 	%rd2, %rd8;
	cvta.to.global.u64 	%rd3, %rd6;
	cvta.to.global.u64 	%rd4, %rd9;
	cvta.to.global.u64 	%rd5, %rd10;
	.loc 1 10 1
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	.loc 1 11 1
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	.loc 1 12 1
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r16, %r17, %r18;
	.loc 1 14 1
	setp.lt.s32	%p1, %r1, %r7;
	setp.lt.s32	%p2, %r2, %r8;
	and.pred  	%p3, %p1, %p2;
	.loc 1 14 1
	setp.lt.s32	%p4, %r3, %r9;
	and.pred  	%p5, %p3, %p4;
	.loc 1 14 1
	@!%p5 bra 	BB0_5;
	bra.uni 	BB0_1;

BB0_1:
	.loc 1 15 1
	mad.lo.s32 	%r19, %r3, %r8, %r2;
	mad.lo.s32 	%r4, %r19, %r7, %r1;
	cvt.s64.s32	%rd11, %r4;
	add.s64 	%rd12, %rd5, %rd11;
	ld.global.s8 	%rd13, [%rd12];
	shl.b64 	%rd14, %rd13, 2;
	add.s64 	%rd15, %rd4, %rd14;
	.loc 1 16 1
	ld.global.f32 	%f1, [%rd15];
	.loc 1 17 1
	setp.ne.s64	%p6, %rd6, 0;
	@%p6 bra 	BB0_3;

	mov.f32 	%f8, 0f3F800000;
	bra.uni 	BB0_4;

BB0_3:
	mul.wide.s32 	%rd16, %r4, 4;
	add.s64 	%rd17, %rd3, %rd16;
	.loc 1 17 1
	ld.global.f32 	%f8, [%rd17];

BB0_4:
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd2, %rd18;
	.loc 1 18 1
	ld.global.f32 	%f5, [%rd19];
	mul.f32 	%f6, %f1, %f8;
	mul.f32 	%f7, %f6, %f5;
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd1, %rd20;
	.loc 1 18 1
	st.global.f32 	[%rd21], %f7;

BB0_5:
	.loc 1 20 2
	ret;
}


`
	copypadmul_ptx_30 = `
.version 3.2
.target sm_30
.address_size 64


.visible .entry copypadmul(
	.param .u64 copypadmul_param_0,
	.param .u32 copypadmul_param_1,
	.param .u32 copypadmul_param_2,
	.param .u32 copypadmul_param_3,
	.param .u64 copypadmul_param_4,
	.param .u64 copypadmul_param_5,
	.param .u32 copypadmul_param_6,
	.param .u32 copypadmul_param_7,
	.param .u32 copypadmul_param_8,
	.param .u64 copypadmul_param_9,
	.param .u64 copypadmul_param_10
)
{
	.reg .pred 	%p<7>;
	.reg .s32 	%r<22>;
	.reg .f32 	%f<9>;
	.reg .s64 	%rd<22>;


	ld.param.u64 	%rd7, [copypadmul_param_0];
	ld.param.u32 	%r5, [copypadmul_param_1];
	ld.param.u32 	%r6, [copypadmul_param_2];
	ld.param.u64 	%rd8, [copypadmul_param_4];
	ld.param.u64 	%rd6, [copypadmul_param_5];
	ld.param.u32 	%r7, [copypadmul_param_6];
	ld.param.u32 	%r8, [copypadmul_param_7];
	ld.param.u32 	%r9, [copypadmul_param_8];
	ld.param.u64 	%rd9, [copypadmul_param_9];
	ld.param.u64 	%rd10, [copypadmul_param_10];
	cvta.to.global.u64 	%rd1, %rd7;
	cvta.to.global.u64 	%rd2, %rd8;
	cvta.to.global.u64 	%rd3, %rd6;
	cvta.to.global.u64 	%rd4, %rd9;
	cvta.to.global.u64 	%rd5, %rd10;
	.loc 1 10 1
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	.loc 1 11 1
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	.loc 1 12 1
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r16, %r17, %r18;
	.loc 1 14 1
	setp.lt.s32	%p1, %r1, %r7;
	setp.lt.s32	%p2, %r2, %r8;
	and.pred  	%p3, %p1, %p2;
	.loc 1 14 1
	setp.lt.s32	%p4, %r3, %r9;
	and.pred  	%p5, %p3, %p4;
	.loc 1 14 1
	@!%p5 bra 	BB0_5;
	bra.uni 	BB0_1;

BB0_1:
	.loc 1 15 1
	mad.lo.s32 	%r19, %r3, %r8, %r2;
	mad.lo.s32 	%r4, %r19, %r7, %r1;
	cvt.s64.s32	%rd11, %r4;
	add.s64 	%rd12, %rd5, %rd11;
	ld.global.s8 	%rd13, [%rd12];
	shl.b64 	%rd14, %rd13, 2;
	add.s64 	%rd15, %rd4, %rd14;
	.loc 1 16 1
	ld.global.f32 	%f1, [%rd15];
	.loc 1 17 1
	setp.ne.s64	%p6, %rd6, 0;
	@%p6 bra 	BB0_3;

	mov.f32 	%f8, 0f3F800000;
	bra.uni 	BB0_4;

BB0_3:
	mul.wide.s32 	%rd16, %r4, 4;
	add.s64 	%rd17, %rd3, %rd16;
	.loc 1 17 1
	ld.global.f32 	%f8, [%rd17];

BB0_4:
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd2, %rd18;
	.loc 1 18 1
	ld.global.f32 	%f5, [%rd19];
	mul.f32 	%f6, %f1, %f8;
	mul.f32 	%f7, %f6, %f5;
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd1, %rd20;
	.loc 1 18 1
	st.global.f32 	[%rd21], %f7;

BB0_5:
	.loc 1 20 2
	ret;
}


`
	copypadmul_ptx_35 = `
.version 3.2
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 66 3
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 71 3
	ret;
}

.visible .entry copypadmul(
	.param .u64 copypadmul_param_0,
	.param .u32 copypadmul_param_1,
	.param .u32 copypadmul_param_2,
	.param .u32 copypadmul_param_3,
	.param .u64 copypadmul_param_4,
	.param .u64 copypadmul_param_5,
	.param .u32 copypadmul_param_6,
	.param .u32 copypadmul_param_7,
	.param .u32 copypadmul_param_8,
	.param .u64 copypadmul_param_9,
	.param .u64 copypadmul_param_10
)
{
	.reg .pred 	%p<7>;
	.reg .s16 	%rs<2>;
	.reg .s32 	%r<22>;
	.reg .f32 	%f<9>;
	.reg .s64 	%rd<23>;


	ld.param.u64 	%rd7, [copypadmul_param_0];
	ld.param.u32 	%r5, [copypadmul_param_1];
	ld.param.u32 	%r6, [copypadmul_param_2];
	ld.param.u64 	%rd8, [copypadmul_param_4];
	ld.param.u64 	%rd6, [copypadmul_param_5];
	ld.param.u32 	%r7, [copypadmul_param_6];
	ld.param.u32 	%r8, [copypadmul_param_7];
	ld.param.u32 	%r9, [copypadmul_param_8];
	ld.param.u64 	%rd9, [copypadmul_param_9];
	ld.param.u64 	%rd10, [copypadmul_param_10];
	cvta.to.global.u64 	%rd1, %rd7;
	cvta.to.global.u64 	%rd2, %rd8;
	cvta.to.global.u64 	%rd3, %rd6;
	cvta.to.global.u64 	%rd4, %rd9;
	cvta.to.global.u64 	%rd5, %rd10;
	.loc 1 10 1
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r10, %r11, %r12;
	.loc 1 11 1
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r13, %r14, %r15;
	.loc 1 12 1
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r16, %r17, %r18;
	.loc 1 14 1
	setp.lt.s32	%p1, %r1, %r7;
	setp.lt.s32	%p2, %r2, %r8;
	and.pred  	%p3, %p1, %p2;
	.loc 1 14 1
	setp.lt.s32	%p4, %r3, %r9;
	and.pred  	%p5, %p3, %p4;
	.loc 1 14 1
	@!%p5 bra 	BB2_5;
	bra.uni 	BB2_1;

BB2_1:
	.loc 1 15 1
	mad.lo.s32 	%r19, %r3, %r8, %r2;
	mad.lo.s32 	%r4, %r19, %r7, %r1;
	cvt.s64.s32	%rd11, %r4;
	add.s64 	%rd12, %rd5, %rd11;
	.loc 1 16 1
	ld.global.nc.u8 	%rs1, [%rd12];
	cvt.u64.u16	%rd13, %rs1;
	cvt.s64.s8 	%rd14, %rd13;
	shl.b64 	%rd15, %rd14, 2;
	add.s64 	%rd16, %rd4, %rd15;
	.loc 1 16 1
	ld.global.nc.f32 	%f1, [%rd16];
	.loc 1 17 1
	setp.ne.s64	%p6, %rd6, 0;
	@%p6 bra 	BB2_3;

	mov.f32 	%f8, 0f3F800000;
	bra.uni 	BB2_4;

BB2_3:
	mul.wide.s32 	%rd17, %r4, 4;
	add.s64 	%rd18, %rd3, %rd17;
	.loc 1 17 1
	ld.global.nc.f32 	%f8, [%rd18];

BB2_4:
	mul.wide.s32 	%rd19, %r4, 4;
	add.s64 	%rd20, %rd2, %rd19;
	.loc 1 18 1
	ld.global.nc.f32 	%f5, [%rd20];
	mul.f32 	%f6, %f1, %f8;
	mul.f32 	%f7, %f6, %f5;
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	mul.wide.s32 	%rd21, %r21, 4;
	add.s64 	%rd22, %rd1, %rd21;
	.loc 1 18 1
	st.global.f32 	[%rd22], %f7;

BB2_5:
	.loc 1 20 2
	ret;
}


`
)
