package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"unsafe"
)

var adddmi_code cu.Function

type adddmi_args struct {
	arg_Hx      unsafe.Pointer
	arg_Hy      unsafe.Pointer
	arg_Hz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_cx      float32
	arg_cy      float32
	arg_cz      float32
	arg_DLUT    unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_N0      int
	arg_N1      int
	arg_N2      int
	argptr      [14]unsafe.Pointer
}

// Wrapper for adddmi CUDA kernel, asynchronous.
func k_adddmi_async(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, cx float32, cy float32, cz float32, DLUT unsafe.Pointer, regions unsafe.Pointer, N0 int, N1 int, N2 int, cfg *config, str cu.Stream) {
	if adddmi_code == 0 {
		adddmi_code = fatbinLoad(adddmi_map, "adddmi")
	}

	var _a_ adddmi_args

	_a_.arg_Hx = Hx
	_a_.argptr[0] = unsafe.Pointer(&_a_.arg_Hx)
	_a_.arg_Hy = Hy
	_a_.argptr[1] = unsafe.Pointer(&_a_.arg_Hy)
	_a_.arg_Hz = Hz
	_a_.argptr[2] = unsafe.Pointer(&_a_.arg_Hz)
	_a_.arg_mx = mx
	_a_.argptr[3] = unsafe.Pointer(&_a_.arg_mx)
	_a_.arg_my = my
	_a_.argptr[4] = unsafe.Pointer(&_a_.arg_my)
	_a_.arg_mz = mz
	_a_.argptr[5] = unsafe.Pointer(&_a_.arg_mz)
	_a_.arg_cx = cx
	_a_.argptr[6] = unsafe.Pointer(&_a_.arg_cx)
	_a_.arg_cy = cy
	_a_.argptr[7] = unsafe.Pointer(&_a_.arg_cy)
	_a_.arg_cz = cz
	_a_.argptr[8] = unsafe.Pointer(&_a_.arg_cz)
	_a_.arg_DLUT = DLUT
	_a_.argptr[9] = unsafe.Pointer(&_a_.arg_DLUT)
	_a_.arg_regions = regions
	_a_.argptr[10] = unsafe.Pointer(&_a_.arg_regions)
	_a_.arg_N0 = N0
	_a_.argptr[11] = unsafe.Pointer(&_a_.arg_N0)
	_a_.arg_N1 = N1
	_a_.argptr[12] = unsafe.Pointer(&_a_.arg_N1)
	_a_.arg_N2 = N2
	_a_.argptr[13] = unsafe.Pointer(&_a_.arg_N2)

	args := _a_.argptr[:]
	cu.LaunchKernel(adddmi_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, str, args)
}

// Wrapper for adddmi CUDA kernel, synchronized.
func k_adddmi(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, cx float32, cy float32, cz float32, DLUT unsafe.Pointer, regions unsafe.Pointer, N0 int, N1 int, N2 int, cfg *config) {
	str := stream()
	k_adddmi_async(Hx, Hy, Hz, mx, my, mz, cx, cy, cz, DLUT, regions, N0, N1, N2, cfg, str)
	syncAndRecycle(str)
}

var adddmi_map = map[int]string{0: "",
	20: adddmi_ptx_20,
	30: adddmi_ptx_30,
	35: adddmi_ptx_35}

const (
	adddmi_ptx_20 = `
.version 3.1
.target sm_20
.address_size 64


.visible .entry adddmi(
	.param .u64 adddmi_param_0,
	.param .u64 adddmi_param_1,
	.param .u64 adddmi_param_2,
	.param .u64 adddmi_param_3,
	.param .u64 adddmi_param_4,
	.param .u64 adddmi_param_5,
	.param .f32 adddmi_param_6,
	.param .f32 adddmi_param_7,
	.param .f32 adddmi_param_8,
	.param .u64 adddmi_param_9,
	.param .u64 adddmi_param_10,
	.param .u32 adddmi_param_11,
	.param .u32 adddmi_param_12,
	.param .u32 adddmi_param_13
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<51>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd8, [adddmi_param_0];
	ld.param.u64 	%rd9, [adddmi_param_1];
	ld.param.u64 	%rd10, [adddmi_param_2];
	ld.param.u64 	%rd11, [adddmi_param_3];
	ld.param.u64 	%rd12, [adddmi_param_4];
	ld.param.u64 	%rd13, [adddmi_param_5];
	ld.param.f32 	%f1, [adddmi_param_7];
	ld.param.f32 	%f2, [adddmi_param_8];
	ld.param.u64 	%rd14, [adddmi_param_9];
	ld.param.u64 	%rd15, [adddmi_param_10];
	ld.param.u32 	%r6, [adddmi_param_11];
	ld.param.u32 	%r4, [adddmi_param_12];
	ld.param.u32 	%r5, [adddmi_param_13];
	cvta.to.global.u64 	%rd1, %rd11;
	cvta.to.global.u64 	%rd2, %rd12;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd14;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd10;
	cvta.to.global.u64 	%rd7, %rd9;
	.loc 2 14 1
	mov.u32 	%r7, %ntid.z;
	mov.u32 	%r8, %ctaid.z;
	mov.u32 	%r9, %tid.z;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 2 15 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 2 16 1
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 2 18 1
	setp.ge.s32 	%p1, %r2, %r4;
	setp.ge.s32 	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	.loc 2 22 1
	mad.lo.s32 	%r16, %r1, %r4, %r2;
	mad.lo.s32 	%r17, %r16, %r5, %r3;
	.loc 2 23 1
	cvt.s64.s32 	%rd16, %r17;
	cvta.to.global.u64 	%rd17, %rd8;
	.loc 2 23 1
	mul.wide.s32 	%rd18, %r17, 4;
	add.s64 	%rd19, %rd17, %rd18;
	add.s64 	%rd20, %rd7, %rd18;
	add.s64 	%rd21, %rd6, %rd18;
	.loc 2 24 1
	add.s64 	%rd22, %rd5, %rd16;
	ld.global.s8 	%rd23, [%rd22];
	shl.b64 	%rd24, %rd23, 2;
	add.s64 	%rd25, %rd4, %rd24;
	.loc 2 27 1
	add.s32 	%r19, %r5, -1;
	add.s32 	%r20, %r3, 1;
	.loc 3 210 5
	min.s32 	%r21, %r20, %r19;
	.loc 2 27 1
	mad.lo.s32 	%r22, %r16, %r5, %r21;
	mul.wide.s32 	%rd26, %r22, 4;
	add.s64 	%rd27, %rd3, %rd26;
	add.s32 	%r23, %r3, -1;
	mov.u32 	%r24, 0;
	.loc 3 238 5
	max.s32 	%r25, %r23, %r24;
	.loc 2 27 1
	mad.lo.s32 	%r26, %r16, %r5, %r25;
	mul.wide.s32 	%rd28, %r26, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.f32 	%f3, [%rd29];
	ld.global.f32 	%f4, [%rd27];
	sub.f32 	%f5, %f4, %f3;
	.loc 2 24 1
	ld.global.f32 	%f6, [%rd25];
	.loc 2 27 1
	mul.f32 	%f7, %f6, %f5;
	.loc 4 2399 3
	div.rn.f32 	%f8, %f7, %f2;
	.loc 2 23 1
	ld.global.f32 	%f9, [%rd19];
	.loc 2 27 1
	add.f32 	%f10, %f9, %f8;
	.loc 2 28 1
	add.s32 	%r31, %r4, -1;
	add.s32 	%r32, %r2, 1;
	.loc 3 210 5
	min.s32 	%r33, %r32, %r31;
	.loc 2 28 1
	mad.lo.s32 	%r34, %r1, %r4, %r33;
	mad.lo.s32 	%r35, %r34, %r5, %r3;
	mul.wide.s32 	%rd30, %r35, 4;
	add.s64 	%rd31, %rd2, %rd30;
	add.s32 	%r36, %r2, -1;
	.loc 3 238 5
	max.s32 	%r37, %r36, %r24;
	.loc 2 28 1
	mad.lo.s32 	%r38, %r1, %r4, %r37;
	mad.lo.s32 	%r39, %r38, %r5, %r3;
	mul.wide.s32 	%rd32, %r39, 4;
	add.s64 	%rd33, %rd2, %rd32;
	ld.global.f32 	%f11, [%rd33];
	ld.global.f32 	%f12, [%rd31];
	sub.f32 	%f13, %f12, %f11;
	mul.f32 	%f14, %f6, %f13;
	.loc 4 2399 3
	div.rn.f32 	%f15, %f14, %f1;
	.loc 2 28 1
	add.f32 	%f16, %f10, %f15;
	.loc 2 29 1
	add.s64 	%rd34, %rd1, %rd30;
	add.s64 	%rd35, %rd1, %rd32;
	ld.global.f32 	%f17, [%rd35];
	ld.global.f32 	%f18, [%rd34];
	sub.f32 	%f19, %f18, %f17;
	mul.f32 	%f20, %f6, %f19;
	.loc 4 2399 3
	div.rn.f32 	%f21, %f20, %f1;
	.loc 2 23 1
	ld.global.f32 	%f22, [%rd20];
	.loc 2 29 1
	sub.f32 	%f23, %f22, %f21;
	.loc 2 30 1
	add.s64 	%rd36, %rd1, %rd26;
	add.s64 	%rd37, %rd1, %rd28;
	ld.global.f32 	%f24, [%rd37];
	ld.global.f32 	%f25, [%rd36];
	sub.f32 	%f26, %f25, %f24;
	mul.f32 	%f27, %f6, %f26;
	.loc 4 2399 3
	div.rn.f32 	%f28, %f27, %f2;
	.loc 2 23 1
	ld.global.f32 	%f29, [%rd21];
	.loc 2 30 1
	sub.f32 	%f30, %f29, %f28;
	.loc 2 34 1
	st.global.f32 	[%rd19], %f16;
	.loc 2 35 1
	st.global.f32 	[%rd20], %f23;
	.loc 2 36 1
	st.global.f32 	[%rd21], %f30;

BB0_2:
	.loc 2 37 2
	ret;
}


`
	adddmi_ptx_30 = `
.version 3.1
.target sm_30
.address_size 64


.visible .entry adddmi(
	.param .u64 adddmi_param_0,
	.param .u64 adddmi_param_1,
	.param .u64 adddmi_param_2,
	.param .u64 adddmi_param_3,
	.param .u64 adddmi_param_4,
	.param .u64 adddmi_param_5,
	.param .f32 adddmi_param_6,
	.param .f32 adddmi_param_7,
	.param .f32 adddmi_param_8,
	.param .u64 adddmi_param_9,
	.param .u64 adddmi_param_10,
	.param .u32 adddmi_param_11,
	.param .u32 adddmi_param_12,
	.param .u32 adddmi_param_13
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<51>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd8, [adddmi_param_0];
	ld.param.u64 	%rd9, [adddmi_param_1];
	ld.param.u64 	%rd10, [adddmi_param_2];
	ld.param.u64 	%rd11, [adddmi_param_3];
	ld.param.u64 	%rd12, [adddmi_param_4];
	ld.param.u64 	%rd13, [adddmi_param_5];
	ld.param.f32 	%f1, [adddmi_param_7];
	ld.param.f32 	%f2, [adddmi_param_8];
	ld.param.u64 	%rd14, [adddmi_param_9];
	ld.param.u64 	%rd15, [adddmi_param_10];
	ld.param.u32 	%r6, [adddmi_param_11];
	ld.param.u32 	%r4, [adddmi_param_12];
	ld.param.u32 	%r5, [adddmi_param_13];
	cvta.to.global.u64 	%rd1, %rd11;
	cvta.to.global.u64 	%rd2, %rd12;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd14;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd10;
	cvta.to.global.u64 	%rd7, %rd9;
	.loc 2 14 1
	mov.u32 	%r7, %ntid.z;
	mov.u32 	%r8, %ctaid.z;
	mov.u32 	%r9, %tid.z;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 2 15 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 2 16 1
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 2 18 1
	setp.ge.s32 	%p1, %r2, %r4;
	setp.ge.s32 	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	.loc 2 22 1
	mad.lo.s32 	%r16, %r1, %r4, %r2;
	mad.lo.s32 	%r17, %r16, %r5, %r3;
	.loc 2 23 1
	cvt.s64.s32 	%rd16, %r17;
	cvta.to.global.u64 	%rd17, %rd8;
	.loc 2 23 1
	mul.wide.s32 	%rd18, %r17, 4;
	add.s64 	%rd19, %rd17, %rd18;
	add.s64 	%rd20, %rd7, %rd18;
	add.s64 	%rd21, %rd6, %rd18;
	.loc 2 24 1
	add.s64 	%rd22, %rd5, %rd16;
	ld.global.s8 	%rd23, [%rd22];
	shl.b64 	%rd24, %rd23, 2;
	add.s64 	%rd25, %rd4, %rd24;
	.loc 2 27 1
	add.s32 	%r19, %r5, -1;
	add.s32 	%r20, %r3, 1;
	.loc 3 210 5
	min.s32 	%r21, %r20, %r19;
	.loc 2 27 1
	mad.lo.s32 	%r22, %r16, %r5, %r21;
	mul.wide.s32 	%rd26, %r22, 4;
	add.s64 	%rd27, %rd3, %rd26;
	add.s32 	%r23, %r3, -1;
	mov.u32 	%r24, 0;
	.loc 3 238 5
	max.s32 	%r25, %r23, %r24;
	.loc 2 27 1
	mad.lo.s32 	%r26, %r16, %r5, %r25;
	mul.wide.s32 	%rd28, %r26, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.f32 	%f3, [%rd29];
	ld.global.f32 	%f4, [%rd27];
	sub.f32 	%f5, %f4, %f3;
	.loc 2 24 1
	ld.global.f32 	%f6, [%rd25];
	.loc 2 27 1
	mul.f32 	%f7, %f6, %f5;
	.loc 4 2399 3
	div.rn.f32 	%f8, %f7, %f2;
	.loc 2 23 1
	ld.global.f32 	%f9, [%rd19];
	.loc 2 27 1
	add.f32 	%f10, %f9, %f8;
	.loc 2 28 1
	add.s32 	%r31, %r4, -1;
	add.s32 	%r32, %r2, 1;
	.loc 3 210 5
	min.s32 	%r33, %r32, %r31;
	.loc 2 28 1
	mad.lo.s32 	%r34, %r1, %r4, %r33;
	mad.lo.s32 	%r35, %r34, %r5, %r3;
	mul.wide.s32 	%rd30, %r35, 4;
	add.s64 	%rd31, %rd2, %rd30;
	add.s32 	%r36, %r2, -1;
	.loc 3 238 5
	max.s32 	%r37, %r36, %r24;
	.loc 2 28 1
	mad.lo.s32 	%r38, %r1, %r4, %r37;
	mad.lo.s32 	%r39, %r38, %r5, %r3;
	mul.wide.s32 	%rd32, %r39, 4;
	add.s64 	%rd33, %rd2, %rd32;
	ld.global.f32 	%f11, [%rd33];
	ld.global.f32 	%f12, [%rd31];
	sub.f32 	%f13, %f12, %f11;
	mul.f32 	%f14, %f6, %f13;
	.loc 4 2399 3
	div.rn.f32 	%f15, %f14, %f1;
	.loc 2 28 1
	add.f32 	%f16, %f10, %f15;
	.loc 2 29 1
	add.s64 	%rd34, %rd1, %rd30;
	add.s64 	%rd35, %rd1, %rd32;
	ld.global.f32 	%f17, [%rd35];
	ld.global.f32 	%f18, [%rd34];
	sub.f32 	%f19, %f18, %f17;
	mul.f32 	%f20, %f6, %f19;
	.loc 4 2399 3
	div.rn.f32 	%f21, %f20, %f1;
	.loc 2 23 1
	ld.global.f32 	%f22, [%rd20];
	.loc 2 29 1
	sub.f32 	%f23, %f22, %f21;
	.loc 2 30 1
	add.s64 	%rd36, %rd1, %rd26;
	add.s64 	%rd37, %rd1, %rd28;
	ld.global.f32 	%f24, [%rd37];
	ld.global.f32 	%f25, [%rd36];
	sub.f32 	%f26, %f25, %f24;
	mul.f32 	%f27, %f6, %f26;
	.loc 4 2399 3
	div.rn.f32 	%f28, %f27, %f2;
	.loc 2 23 1
	ld.global.f32 	%f29, [%rd21];
	.loc 2 30 1
	sub.f32 	%f30, %f29, %f28;
	.loc 2 34 1
	st.global.f32 	[%rd19], %f16;
	.loc 2 35 1
	st.global.f32 	[%rd20], %f23;
	.loc 2 36 1
	st.global.f32 	[%rd21], %f30;

BB0_2:
	.loc 2 37 2
	ret;
}


`
	adddmi_ptx_35 = `
.version 3.1
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 66 3
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 71 3
	ret;
}

.visible .entry adddmi(
	.param .u64 adddmi_param_0,
	.param .u64 adddmi_param_1,
	.param .u64 adddmi_param_2,
	.param .u64 adddmi_param_3,
	.param .u64 adddmi_param_4,
	.param .u64 adddmi_param_5,
	.param .f32 adddmi_param_6,
	.param .f32 adddmi_param_7,
	.param .f32 adddmi_param_8,
	.param .u64 adddmi_param_9,
	.param .u64 adddmi_param_10,
	.param .u32 adddmi_param_11,
	.param .u32 adddmi_param_12,
	.param .u32 adddmi_param_13
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<39>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd8, [adddmi_param_0];
	ld.param.u64 	%rd9, [adddmi_param_1];
	ld.param.u64 	%rd10, [adddmi_param_2];
	ld.param.u64 	%rd11, [adddmi_param_3];
	ld.param.u64 	%rd12, [adddmi_param_4];
	ld.param.u64 	%rd13, [adddmi_param_5];
	ld.param.f32 	%f1, [adddmi_param_7];
	ld.param.f32 	%f2, [adddmi_param_8];
	ld.param.u64 	%rd14, [adddmi_param_9];
	ld.param.u64 	%rd15, [adddmi_param_10];
	ld.param.u32 	%r6, [adddmi_param_11];
	ld.param.u32 	%r4, [adddmi_param_12];
	ld.param.u32 	%r5, [adddmi_param_13];
	cvta.to.global.u64 	%rd1, %rd11;
	cvta.to.global.u64 	%rd2, %rd12;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd14;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd10;
	cvta.to.global.u64 	%rd7, %rd9;
	.loc 3 14 1
	mov.u32 	%r7, %ntid.z;
	mov.u32 	%r8, %ctaid.z;
	mov.u32 	%r9, %tid.z;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 3 15 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 3 16 1
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 3 18 1
	setp.ge.s32 	%p1, %r2, %r4;
	setp.ge.s32 	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r5;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB2_2;

	.loc 3 22 1
	mad.lo.s32 	%r16, %r1, %r4, %r2;
	mad.lo.s32 	%r17, %r16, %r5, %r3;
	.loc 3 23 1
	cvt.s64.s32 	%rd16, %r17;
	cvta.to.global.u64 	%rd17, %rd8;
	.loc 3 23 1
	mul.wide.s32 	%rd18, %r17, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f3, [%rd19];
	add.s64 	%rd20, %rd7, %rd18;
	ld.global.nc.f32 	%f4, [%rd20];
	add.s64 	%rd21, %rd6, %rd18;
	ld.global.nc.f32 	%f5, [%rd21];
	.loc 3 24 1
	add.s64 	%rd22, %rd5, %rd16;
	ld.global.s8 	%rd23, [%rd22];
	shl.b64 	%rd24, %rd23, 2;
	add.s64 	%rd25, %rd4, %rd24;
	ld.global.nc.f32 	%f6, [%rd25];
	.loc 3 27 1
	add.s32 	%r19, %r5, -1;
	add.s32 	%r20, %r3, 1;
	.loc 4 210 5
	min.s32 	%r21, %r20, %r19;
	.loc 3 27 1
	mad.lo.s32 	%r22, %r16, %r5, %r21;
	mul.wide.s32 	%rd26, %r22, 4;
	add.s64 	%rd27, %rd3, %rd26;
	ld.global.nc.f32 	%f7, [%rd27];
	add.s32 	%r23, %r3, -1;
	mov.u32 	%r24, 0;
	.loc 4 238 5
	max.s32 	%r25, %r23, %r24;
	.loc 3 27 1
	mad.lo.s32 	%r26, %r16, %r5, %r25;
	mul.wide.s32 	%rd28, %r26, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.nc.f32 	%f8, [%rd29];
	sub.f32 	%f9, %f7, %f8;
	mul.f32 	%f10, %f6, %f9;
	.loc 5 2399 3
	div.rn.f32 	%f11, %f10, %f2;
	.loc 3 27 1
	add.f32 	%f12, %f3, %f11;
	.loc 3 28 1
	add.s32 	%r27, %r4, -1;
	add.s32 	%r28, %r2, 1;
	.loc 4 210 5
	min.s32 	%r29, %r28, %r27;
	.loc 3 28 1
	mad.lo.s32 	%r30, %r1, %r4, %r29;
	mad.lo.s32 	%r31, %r30, %r5, %r3;
	mul.wide.s32 	%rd30, %r31, 4;
	add.s64 	%rd31, %rd2, %rd30;
	ld.global.nc.f32 	%f13, [%rd31];
	add.s32 	%r32, %r2, -1;
	.loc 4 238 5
	max.s32 	%r33, %r32, %r24;
	.loc 3 28 1
	mad.lo.s32 	%r34, %r1, %r4, %r33;
	mad.lo.s32 	%r35, %r34, %r5, %r3;
	mul.wide.s32 	%rd32, %r35, 4;
	add.s64 	%rd33, %rd2, %rd32;
	ld.global.nc.f32 	%f14, [%rd33];
	sub.f32 	%f15, %f13, %f14;
	mul.f32 	%f16, %f6, %f15;
	.loc 5 2399 3
	div.rn.f32 	%f17, %f16, %f1;
	.loc 3 28 1
	add.f32 	%f18, %f12, %f17;
	.loc 3 29 1
	add.s64 	%rd34, %rd1, %rd30;
	ld.global.nc.f32 	%f19, [%rd34];
	add.s64 	%rd35, %rd1, %rd32;
	ld.global.nc.f32 	%f20, [%rd35];
	sub.f32 	%f21, %f19, %f20;
	mul.f32 	%f22, %f6, %f21;
	.loc 5 2399 3
	div.rn.f32 	%f23, %f22, %f1;
	.loc 3 29 1
	sub.f32 	%f24, %f4, %f23;
	.loc 3 30 1
	add.s64 	%rd36, %rd1, %rd26;
	ld.global.nc.f32 	%f25, [%rd36];
	add.s64 	%rd37, %rd1, %rd28;
	ld.global.nc.f32 	%f26, [%rd37];
	sub.f32 	%f27, %f25, %f26;
	mul.f32 	%f28, %f6, %f27;
	.loc 5 2399 3
	div.rn.f32 	%f29, %f28, %f2;
	.loc 3 30 1
	sub.f32 	%f30, %f5, %f29;
	.loc 3 34 1
	st.global.f32 	[%rd19], %f18;
	.loc 3 35 1
	st.global.f32 	[%rd20], %f24;
	.loc 3 36 1
	st.global.f32 	[%rd21], %f30;

BB2_2:
	.loc 3 37 2
	ret;
}


`
)
