package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"sync"
	"unsafe"
)

// CUDA handle for kernmulRSymm3D kernel
var kernmulRSymm3D_code cu.Function

// Stores the arguments for kernmulRSymm3D kernel invocation
type kernmulRSymm3D_args_t struct {
	arg_fftMx  unsafe.Pointer
	arg_fftMy  unsafe.Pointer
	arg_fftMz  unsafe.Pointer
	arg_fftKxx unsafe.Pointer
	arg_fftKyy unsafe.Pointer
	arg_fftKzz unsafe.Pointer
	arg_fftKyz unsafe.Pointer
	arg_fftKxz unsafe.Pointer
	arg_fftKxy unsafe.Pointer
	arg_Nx     int
	arg_Ny     int
	arg_Nz     int
	argptr     [12]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for kernmulRSymm3D kernel invocation
var kernmulRSymm3D_args kernmulRSymm3D_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	kernmulRSymm3D_args.argptr[0] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftMx)
	kernmulRSymm3D_args.argptr[1] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftMy)
	kernmulRSymm3D_args.argptr[2] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftMz)
	kernmulRSymm3D_args.argptr[3] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKxx)
	kernmulRSymm3D_args.argptr[4] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKyy)
	kernmulRSymm3D_args.argptr[5] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKzz)
	kernmulRSymm3D_args.argptr[6] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKyz)
	kernmulRSymm3D_args.argptr[7] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKxz)
	kernmulRSymm3D_args.argptr[8] = unsafe.Pointer(&kernmulRSymm3D_args.arg_fftKxy)
	kernmulRSymm3D_args.argptr[9] = unsafe.Pointer(&kernmulRSymm3D_args.arg_Nx)
	kernmulRSymm3D_args.argptr[10] = unsafe.Pointer(&kernmulRSymm3D_args.arg_Ny)
	kernmulRSymm3D_args.argptr[11] = unsafe.Pointer(&kernmulRSymm3D_args.arg_Nz)
}

// Wrapper for kernmulRSymm3D CUDA kernel, asynchronous.
func k_kernmulRSymm3D_async(fftMx unsafe.Pointer, fftMy unsafe.Pointer, fftMz unsafe.Pointer, fftKxx unsafe.Pointer, fftKyy unsafe.Pointer, fftKzz unsafe.Pointer, fftKyz unsafe.Pointer, fftKxz unsafe.Pointer, fftKxy unsafe.Pointer, Nx int, Ny int, Nz int, cfg *config) {
	if Synchronous { // debug
		Sync()
	}

	kernmulRSymm3D_args.Lock()
	defer kernmulRSymm3D_args.Unlock()

	if kernmulRSymm3D_code == 0 {
		kernmulRSymm3D_code = fatbinLoad(kernmulRSymm3D_map, "kernmulRSymm3D")
	}

	kernmulRSymm3D_args.arg_fftMx = fftMx
	kernmulRSymm3D_args.arg_fftMy = fftMy
	kernmulRSymm3D_args.arg_fftMz = fftMz
	kernmulRSymm3D_args.arg_fftKxx = fftKxx
	kernmulRSymm3D_args.arg_fftKyy = fftKyy
	kernmulRSymm3D_args.arg_fftKzz = fftKzz
	kernmulRSymm3D_args.arg_fftKyz = fftKyz
	kernmulRSymm3D_args.arg_fftKxz = fftKxz
	kernmulRSymm3D_args.arg_fftKxy = fftKxy
	kernmulRSymm3D_args.arg_Nx = Nx
	kernmulRSymm3D_args.arg_Ny = Ny
	kernmulRSymm3D_args.arg_Nz = Nz

	args := kernmulRSymm3D_args.argptr[:]
	cu.LaunchKernel(kernmulRSymm3D_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
	}
}

// maps compute capability on PTX code for kernmulRSymm3D kernel.
var kernmulRSymm3D_map = map[int]string{0: "",
	20: kernmulRSymm3D_ptx_20,
	30: kernmulRSymm3D_ptx_30,
	35: kernmulRSymm3D_ptx_35}

// kernmulRSymm3D PTX code for various compute capabilities.
const (
	kernmulRSymm3D_ptx_20 = `
.version 3.2
.target sm_20
.address_size 64


.visible .entry kernmulRSymm3D(
	.param .u64 kernmulRSymm3D_param_0,
	.param .u64 kernmulRSymm3D_param_1,
	.param .u64 kernmulRSymm3D_param_2,
	.param .u64 kernmulRSymm3D_param_3,
	.param .u64 kernmulRSymm3D_param_4,
	.param .u64 kernmulRSymm3D_param_5,
	.param .u64 kernmulRSymm3D_param_6,
	.param .u64 kernmulRSymm3D_param_7,
	.param .u64 kernmulRSymm3D_param_8,
	.param .u32 kernmulRSymm3D_param_9,
	.param .u32 kernmulRSymm3D_param_10,
	.param .u32 kernmulRSymm3D_param_11
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<19>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<30>;


	ld.param.u64 	%rd8, [kernmulRSymm3D_param_0];
	ld.param.u64 	%rd9, [kernmulRSymm3D_param_1];
	ld.param.u64 	%rd10, [kernmulRSymm3D_param_2];
	ld.param.u64 	%rd11, [kernmulRSymm3D_param_3];
	ld.param.u64 	%rd12, [kernmulRSymm3D_param_4];
	ld.param.u64 	%rd13, [kernmulRSymm3D_param_5];
	ld.param.u64 	%rd14, [kernmulRSymm3D_param_6];
	ld.param.u64 	%rd15, [kernmulRSymm3D_param_7];
	ld.param.u64 	%rd16, [kernmulRSymm3D_param_8];
	ld.param.u32 	%r4, [kernmulRSymm3D_param_9];
	ld.param.u32 	%r5, [kernmulRSymm3D_param_10];
	ld.param.u32 	%r6, [kernmulRSymm3D_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd13;
	cvta.to.global.u64 	%rd5, %rd12;
	cvta.to.global.u64 	%rd6, %rd11;
	cvta.to.global.u64 	%rd7, %rd10;
	.loc 1 35 1
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 1 36 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 1 37 1
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 1 39 1
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p2, %p1;
	.loc 1 39 1
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	.loc 1 39 1
	@%p5 bra 	BB0_2;

	.loc 1 45 1
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	.loc 1 46 1
	shl.b32 	%r18, %r17, 1;
	cvta.to.global.u64 	%rd17, %rd8;
	mul.wide.s32 	%rd18, %r18, 4;
	add.s64 	%rd19, %rd17, %rd18;
	.loc 1 48 1
	ld.global.f32 	%f1, [%rd19+4];
	cvta.to.global.u64 	%rd20, %rd9;
	add.s64 	%rd21, %rd20, %rd18;
	.loc 1 50 1
	ld.global.f32 	%f2, [%rd21+4];
	add.s64 	%rd22, %rd7, %rd18;
	.loc 1 52 1
	ld.global.f32 	%f3, [%rd22+4];
	mul.wide.s32 	%rd23, %r17, 4;
	add.s64 	%rd24, %rd6, %rd23;
	add.s64 	%rd25, %rd5, %rd23;
	.loc 1 56 1
	ld.global.f32 	%f4, [%rd25];
	add.s64 	%rd26, %rd4, %rd23;
	.loc 1 57 1
	ld.global.f32 	%f5, [%rd26];
	add.s64 	%rd27, %rd3, %rd23;
	.loc 1 58 1
	ld.global.f32 	%f6, [%rd27];
	add.s64 	%rd28, %rd2, %rd23;
	add.s64 	%rd29, %rd1, %rd23;
	.loc 1 55 1
	ld.global.f32 	%f7, [%rd24];
	.loc 1 47 1
	ld.global.f32 	%f8, [%rd19];
	.loc 1 60 1
	ld.global.f32 	%f9, [%rd29];
	.loc 1 49 1
	ld.global.f32 	%f10, [%rd21];
	.loc 1 62 1
	mul.f32 	%f11, %f10, %f9;
	fma.rn.f32 	%f12, %f8, %f7, %f11;
	.loc 1 59 1
	ld.global.f32 	%f13, [%rd28];
	.loc 1 51 1
	ld.global.f32 	%f14, [%rd22];
	.loc 1 62 1
	fma.rn.f32 	%f15, %f14, %f13, %f12;
	st.global.f32 	[%rd19], %f15;
	.loc 1 63 1
	mul.f32 	%f16, %f2, %f9;
	fma.rn.f32 	%f17, %f1, %f7, %f16;
	fma.rn.f32 	%f18, %f3, %f13, %f17;
	st.global.f32 	[%rd19+4], %f18;
	.loc 1 64 1
	mul.f32 	%f19, %f10, %f4;
	fma.rn.f32 	%f20, %f8, %f9, %f19;
	fma.rn.f32 	%f21, %f14, %f6, %f20;
	st.global.f32 	[%rd21], %f21;
	.loc 1 65 1
	mul.f32 	%f22, %f2, %f4;
	fma.rn.f32 	%f23, %f1, %f9, %f22;
	fma.rn.f32 	%f24, %f3, %f6, %f23;
	st.global.f32 	[%rd21+4], %f24;
	.loc 1 66 1
	mul.f32 	%f25, %f10, %f6;
	fma.rn.f32 	%f26, %f8, %f13, %f25;
	fma.rn.f32 	%f27, %f14, %f5, %f26;
	st.global.f32 	[%rd22], %f27;
	.loc 1 67 1
	mul.f32 	%f28, %f2, %f6;
	fma.rn.f32 	%f29, %f1, %f13, %f28;
	fma.rn.f32 	%f30, %f3, %f5, %f29;
	st.global.f32 	[%rd22+4], %f30;

BB0_2:
	.loc 1 68 2
	ret;
}


`
	kernmulRSymm3D_ptx_30 = `
.version 3.2
.target sm_30
.address_size 64


.visible .entry kernmulRSymm3D(
	.param .u64 kernmulRSymm3D_param_0,
	.param .u64 kernmulRSymm3D_param_1,
	.param .u64 kernmulRSymm3D_param_2,
	.param .u64 kernmulRSymm3D_param_3,
	.param .u64 kernmulRSymm3D_param_4,
	.param .u64 kernmulRSymm3D_param_5,
	.param .u64 kernmulRSymm3D_param_6,
	.param .u64 kernmulRSymm3D_param_7,
	.param .u64 kernmulRSymm3D_param_8,
	.param .u32 kernmulRSymm3D_param_9,
	.param .u32 kernmulRSymm3D_param_10,
	.param .u32 kernmulRSymm3D_param_11
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<19>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<30>;


	ld.param.u64 	%rd8, [kernmulRSymm3D_param_0];
	ld.param.u64 	%rd9, [kernmulRSymm3D_param_1];
	ld.param.u64 	%rd10, [kernmulRSymm3D_param_2];
	ld.param.u64 	%rd11, [kernmulRSymm3D_param_3];
	ld.param.u64 	%rd12, [kernmulRSymm3D_param_4];
	ld.param.u64 	%rd13, [kernmulRSymm3D_param_5];
	ld.param.u64 	%rd14, [kernmulRSymm3D_param_6];
	ld.param.u64 	%rd15, [kernmulRSymm3D_param_7];
	ld.param.u64 	%rd16, [kernmulRSymm3D_param_8];
	ld.param.u32 	%r4, [kernmulRSymm3D_param_9];
	ld.param.u32 	%r5, [kernmulRSymm3D_param_10];
	ld.param.u32 	%r6, [kernmulRSymm3D_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd13;
	cvta.to.global.u64 	%rd5, %rd12;
	cvta.to.global.u64 	%rd6, %rd11;
	cvta.to.global.u64 	%rd7, %rd10;
	.loc 1 35 1
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 1 36 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 1 37 1
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 1 39 1
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p2, %p1;
	.loc 1 39 1
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	.loc 1 39 1
	@%p5 bra 	BB0_2;

	.loc 1 45 1
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	.loc 1 46 1
	shl.b32 	%r18, %r17, 1;
	cvta.to.global.u64 	%rd17, %rd8;
	mul.wide.s32 	%rd18, %r18, 4;
	add.s64 	%rd19, %rd17, %rd18;
	.loc 1 48 1
	ld.global.f32 	%f1, [%rd19+4];
	cvta.to.global.u64 	%rd20, %rd9;
	add.s64 	%rd21, %rd20, %rd18;
	.loc 1 50 1
	ld.global.f32 	%f2, [%rd21+4];
	add.s64 	%rd22, %rd7, %rd18;
	.loc 1 52 1
	ld.global.f32 	%f3, [%rd22+4];
	mul.wide.s32 	%rd23, %r17, 4;
	add.s64 	%rd24, %rd6, %rd23;
	add.s64 	%rd25, %rd5, %rd23;
	.loc 1 56 1
	ld.global.f32 	%f4, [%rd25];
	add.s64 	%rd26, %rd4, %rd23;
	.loc 1 57 1
	ld.global.f32 	%f5, [%rd26];
	add.s64 	%rd27, %rd3, %rd23;
	.loc 1 58 1
	ld.global.f32 	%f6, [%rd27];
	add.s64 	%rd28, %rd2, %rd23;
	add.s64 	%rd29, %rd1, %rd23;
	.loc 1 55 1
	ld.global.f32 	%f7, [%rd24];
	.loc 1 47 1
	ld.global.f32 	%f8, [%rd19];
	.loc 1 60 1
	ld.global.f32 	%f9, [%rd29];
	.loc 1 49 1
	ld.global.f32 	%f10, [%rd21];
	.loc 1 62 1
	mul.f32 	%f11, %f10, %f9;
	fma.rn.f32 	%f12, %f8, %f7, %f11;
	.loc 1 59 1
	ld.global.f32 	%f13, [%rd28];
	.loc 1 51 1
	ld.global.f32 	%f14, [%rd22];
	.loc 1 62 1
	fma.rn.f32 	%f15, %f14, %f13, %f12;
	st.global.f32 	[%rd19], %f15;
	.loc 1 63 1
	mul.f32 	%f16, %f2, %f9;
	fma.rn.f32 	%f17, %f1, %f7, %f16;
	fma.rn.f32 	%f18, %f3, %f13, %f17;
	st.global.f32 	[%rd19+4], %f18;
	.loc 1 64 1
	mul.f32 	%f19, %f10, %f4;
	fma.rn.f32 	%f20, %f8, %f9, %f19;
	fma.rn.f32 	%f21, %f14, %f6, %f20;
	st.global.f32 	[%rd21], %f21;
	.loc 1 65 1
	mul.f32 	%f22, %f2, %f4;
	fma.rn.f32 	%f23, %f1, %f9, %f22;
	fma.rn.f32 	%f24, %f3, %f6, %f23;
	st.global.f32 	[%rd21+4], %f24;
	.loc 1 66 1
	mul.f32 	%f25, %f10, %f6;
	fma.rn.f32 	%f26, %f8, %f13, %f25;
	fma.rn.f32 	%f27, %f14, %f5, %f26;
	st.global.f32 	[%rd22], %f27;
	.loc 1 67 1
	mul.f32 	%f28, %f2, %f6;
	fma.rn.f32 	%f29, %f1, %f13, %f28;
	fma.rn.f32 	%f30, %f3, %f5, %f29;
	st.global.f32 	[%rd22+4], %f30;

BB0_2:
	.loc 1 68 2
	ret;
}


`
	kernmulRSymm3D_ptx_35 = `
.version 3.2
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 66 3
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 71 3
	ret;
}

.visible .entry kernmulRSymm3D(
	.param .u64 kernmulRSymm3D_param_0,
	.param .u64 kernmulRSymm3D_param_1,
	.param .u64 kernmulRSymm3D_param_2,
	.param .u64 kernmulRSymm3D_param_3,
	.param .u64 kernmulRSymm3D_param_4,
	.param .u64 kernmulRSymm3D_param_5,
	.param .u64 kernmulRSymm3D_param_6,
	.param .u64 kernmulRSymm3D_param_7,
	.param .u64 kernmulRSymm3D_param_8,
	.param .u32 kernmulRSymm3D_param_9,
	.param .u32 kernmulRSymm3D_param_10,
	.param .u32 kernmulRSymm3D_param_11
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<19>;
	.reg .f32 	%f<31>;
	.reg .s64 	%rd<30>;


	ld.param.u64 	%rd8, [kernmulRSymm3D_param_0];
	ld.param.u64 	%rd9, [kernmulRSymm3D_param_1];
	ld.param.u64 	%rd10, [kernmulRSymm3D_param_2];
	ld.param.u64 	%rd11, [kernmulRSymm3D_param_3];
	ld.param.u64 	%rd12, [kernmulRSymm3D_param_4];
	ld.param.u64 	%rd13, [kernmulRSymm3D_param_5];
	ld.param.u64 	%rd14, [kernmulRSymm3D_param_6];
	ld.param.u64 	%rd15, [kernmulRSymm3D_param_7];
	ld.param.u64 	%rd16, [kernmulRSymm3D_param_8];
	ld.param.u32 	%r4, [kernmulRSymm3D_param_9];
	ld.param.u32 	%r5, [kernmulRSymm3D_param_10];
	ld.param.u32 	%r6, [kernmulRSymm3D_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd13;
	cvta.to.global.u64 	%rd5, %rd12;
	cvta.to.global.u64 	%rd6, %rd11;
	cvta.to.global.u64 	%rd7, %rd10;
	.loc 1 35 1
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r7, %r8, %r9;
	.loc 1 36 1
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	.loc 1 37 1
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	.loc 1 39 1
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p2, %p1;
	.loc 1 39 1
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	.loc 1 39 1
	@%p5 bra 	BB2_2;

	.loc 1 45 1
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	.loc 1 46 1
	shl.b32 	%r18, %r17, 1;
	cvta.to.global.u64 	%rd17, %rd8;
	mul.wide.s32 	%rd18, %r18, 4;
	add.s64 	%rd19, %rd17, %rd18;
	.loc 1 48 1
	ld.global.f32 	%f1, [%rd19+4];
	cvta.to.global.u64 	%rd20, %rd9;
	add.s64 	%rd21, %rd20, %rd18;
	.loc 1 50 1
	ld.global.f32 	%f2, [%rd21+4];
	add.s64 	%rd22, %rd7, %rd18;
	.loc 1 52 1
	ld.global.f32 	%f3, [%rd22+4];
	mul.wide.s32 	%rd23, %r17, 4;
	add.s64 	%rd24, %rd6, %rd23;
	add.s64 	%rd25, %rd5, %rd23;
	.loc 1 56 1
	ld.global.nc.f32 	%f4, [%rd25];
	add.s64 	%rd26, %rd4, %rd23;
	.loc 1 57 1
	ld.global.nc.f32 	%f5, [%rd26];
	add.s64 	%rd27, %rd3, %rd23;
	.loc 1 58 1
	ld.global.nc.f32 	%f6, [%rd27];
	add.s64 	%rd28, %rd2, %rd23;
	add.s64 	%rd29, %rd1, %rd23;
	.loc 1 55 1
	ld.global.nc.f32 	%f7, [%rd24];
	.loc 1 47 1
	ld.global.f32 	%f8, [%rd19];
	.loc 1 60 1
	ld.global.nc.f32 	%f9, [%rd29];
	.loc 1 49 1
	ld.global.f32 	%f10, [%rd21];
	.loc 1 62 1
	mul.f32 	%f11, %f10, %f9;
	fma.rn.f32 	%f12, %f8, %f7, %f11;
	.loc 1 59 1
	ld.global.nc.f32 	%f13, [%rd28];
	.loc 1 51 1
	ld.global.f32 	%f14, [%rd22];
	.loc 1 62 1
	fma.rn.f32 	%f15, %f14, %f13, %f12;
	st.global.f32 	[%rd19], %f15;
	.loc 1 63 1
	mul.f32 	%f16, %f2, %f9;
	fma.rn.f32 	%f17, %f1, %f7, %f16;
	fma.rn.f32 	%f18, %f3, %f13, %f17;
	st.global.f32 	[%rd19+4], %f18;
	.loc 1 64 1
	mul.f32 	%f19, %f10, %f4;
	fma.rn.f32 	%f20, %f8, %f9, %f19;
	fma.rn.f32 	%f21, %f14, %f6, %f20;
	st.global.f32 	[%rd21], %f21;
	.loc 1 65 1
	mul.f32 	%f22, %f2, %f4;
	fma.rn.f32 	%f23, %f1, %f9, %f22;
	fma.rn.f32 	%f24, %f3, %f6, %f23;
	st.global.f32 	[%rd21+4], %f24;
	.loc 1 66 1
	mul.f32 	%f25, %f10, %f6;
	fma.rn.f32 	%f26, %f8, %f13, %f25;
	fma.rn.f32 	%f27, %f14, %f5, %f26;
	st.global.f32 	[%rd22], %f27;
	.loc 1 67 1
	mul.f32 	%f28, %f2, %f6;
	fma.rn.f32 	%f29, %f1, %f13, %f28;
	fma.rn.f32 	%f30, %f3, %f5, %f29;
	st.global.f32 	[%rd22+4], %f30;

BB2_2:
	.loc 1 68 2
	ret;
}


`
)
