package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for reducedot kernel
var reducedot_code cu.Function

// Stores the arguments for reducedot kernel invocation
type reducedot_args_t struct {
	arg_x1      unsafe.Pointer
	arg_x2      unsafe.Pointer
	arg_dst     unsafe.Pointer
	arg_initVal float32
	arg_n       int
	argptr      [5]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for reducedot kernel invocation
var reducedot_args reducedot_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	reducedot_args.argptr[0] = unsafe.Pointer(&reducedot_args.arg_x1)
	reducedot_args.argptr[1] = unsafe.Pointer(&reducedot_args.arg_x2)
	reducedot_args.argptr[2] = unsafe.Pointer(&reducedot_args.arg_dst)
	reducedot_args.argptr[3] = unsafe.Pointer(&reducedot_args.arg_initVal)
	reducedot_args.argptr[4] = unsafe.Pointer(&reducedot_args.arg_n)
}

// Wrapper for reducedot CUDA kernel, asynchronous.
func k_reducedot_async(x1 unsafe.Pointer, x2 unsafe.Pointer, dst unsafe.Pointer, initVal float32, n int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("reducedot")
	}

	reducedot_args.Lock()
	defer reducedot_args.Unlock()

	if reducedot_code == 0 {
		reducedot_code = fatbinLoad(reducedot_map, "reducedot")
	}

	reducedot_args.arg_x1 = x1
	reducedot_args.arg_x2 = x2
	reducedot_args.arg_dst = dst
	reducedot_args.arg_initVal = initVal
	reducedot_args.arg_n = n

	args := reducedot_args.argptr[:]
	cu.LaunchKernel(reducedot_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("reducedot")
	}
}

// maps compute capability on PTX code for reducedot kernel.
var reducedot_map = map[int]string{0: "",
	20: reducedot_ptx_20,
	30: reducedot_ptx_30,
	35: reducedot_ptx_35,
	50: reducedot_ptx_50,
	52: reducedot_ptx_52,
	53: reducedot_ptx_53,
	60: reducedot_ptx_60,
	61: reducedot_ptx_61}

// reducedot PTX code for various compute capabilities.
const (
	reducedot_ptx_20 = `
.version 4.3
.target sm_20
.address_size 64

	// .globl	reducedot

.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42198_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB0_2;

BB0_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.f32 	%f5, [%rd9];
	ld.global.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB0_1;

BB0_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42198_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB0_6;

BB0_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB0_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB0_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB0_3;

BB0_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB0_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB0_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB0_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42198_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB0_10:
	ret;
}


`
	reducedot_ptx_30 = `
.version 4.3
.target sm_30
.address_size 64

	// .globl	reducedot

.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42494_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB0_2;

BB0_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.f32 	%f5, [%rd9];
	ld.global.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB0_1;

BB0_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42494_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB0_6;

BB0_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB0_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB0_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB0_3;

BB0_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB0_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB0_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB0_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42494_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB0_10:
	ret;
}


`
	reducedot_ptx_35 = `
.version 4.3
.target sm_35
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	reducedot
.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42751_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB6_2;

BB6_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB6_1;

BB6_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42751_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB6_6;

BB6_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB6_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB6_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB6_3;

BB6_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB6_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB6_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB6_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42751_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB6_10:
	ret;
}


`
	reducedot_ptx_50 = `
.version 4.3
.target sm_50
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	reducedot
.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42751_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB6_2;

BB6_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB6_1;

BB6_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42751_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB6_6;

BB6_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB6_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB6_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB6_3;

BB6_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB6_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB6_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB6_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42751_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB6_10:
	ret;
}


`
	reducedot_ptx_52 = `
.version 4.3
.target sm_52
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	reducedot
.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42751_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB6_2;

BB6_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB6_1;

BB6_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42751_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB6_6;

BB6_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB6_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB6_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB6_3;

BB6_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB6_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB6_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB6_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42751_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB6_10:
	ret;
}


`
	reducedot_ptx_53 = `
.version 4.3
.target sm_53
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	reducedot
.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_42751_10_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB6_2;

BB6_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB6_1;

BB6_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_42751_10_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB6_6;

BB6_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB6_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB6_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB6_3;

BB6_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB6_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB6_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB6_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_42751_10_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB6_10:
	ret;
}


`
	reducedot_ptx_60 = `
.version 5.0
.target sm_60
.address_size 64

	// .globl	reducedot

.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_18187_35_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB0_2;

BB0_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB0_1;

BB0_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_18187_35_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB0_6;

BB0_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB0_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB0_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB0_3;

BB0_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB0_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB0_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB0_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_18187_35_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB0_10:
	ret;
}


`
	reducedot_ptx_61 = `
.version 5.0
.target sm_61
.address_size 64

	// .globl	reducedot

.visible .entry reducedot(
	.param .u64 reducedot_param_0,
	.param .u64 reducedot_param_1,
	.param .u64 reducedot_param_2,
	.param .f32 reducedot_param_3,
	.param .u32 reducedot_param_4
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<16>;
	// demoted variable
	.shared .align 4 .b8 reducedot$__cuda_local_var_18290_35_non_const_sdata[2048];

	ld.param.u64 	%rd5, [reducedot_param_0];
	ld.param.u64 	%rd6, [reducedot_param_1];
	ld.param.u64 	%rd4, [reducedot_param_2];
	ld.param.f32 	%f30, [reducedot_param_3];
	ld.param.u32 	%r9, [reducedot_param_4];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	mad.lo.s32 	%r13, %r14, %r10, %r2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r4, %r11, %r14;
	setp.ge.s32	%p1, %r13, %r9;
	@%p1 bra 	BB0_2;

BB0_1:
	mul.wide.s32 	%rd7, %r13, 4;
	add.s64 	%rd8, %rd2, %rd7;
	add.s64 	%rd9, %rd1, %rd7;
	ld.global.nc.f32 	%f5, [%rd9];
	ld.global.nc.f32 	%f6, [%rd8];
	fma.rn.f32 	%f30, %f6, %f5, %f30;
	add.s32 	%r13, %r13, %r4;
	setp.lt.s32	%p2, %r13, %r9;
	@%p2 bra 	BB0_1;

BB0_2:
	mul.wide.s32 	%rd10, %r2, 4;
	mov.u64 	%rd11, reducedot$__cuda_local_var_18290_35_non_const_sdata;
	add.s64 	%rd3, %rd11, %rd10;
	st.shared.f32 	[%rd3], %f30;
	bar.sync 	0;
	setp.lt.u32	%p3, %r14, 66;
	@%p3 bra 	BB0_6;

BB0_3:
	mov.u32 	%r7, %r14;
	shr.u32 	%r14, %r7, 1;
	setp.ge.u32	%p4, %r2, %r14;
	@%p4 bra 	BB0_5;

	ld.shared.f32 	%f7, [%rd3];
	add.s32 	%r12, %r14, %r2;
	mul.wide.u32 	%rd12, %r12, 4;
	add.s64 	%rd14, %rd11, %rd12;
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f7, %f8;
	st.shared.f32 	[%rd3], %f9;

BB0_5:
	bar.sync 	0;
	setp.gt.u32	%p5, %r7, 131;
	@%p5 bra 	BB0_3;

BB0_6:
	setp.gt.s32	%p6, %r2, 31;
	@%p6 bra 	BB0_8;

	ld.volatile.shared.f32 	%f10, [%rd3];
	ld.volatile.shared.f32 	%f11, [%rd3+128];
	add.f32 	%f12, %f10, %f11;
	st.volatile.shared.f32 	[%rd3], %f12;
	ld.volatile.shared.f32 	%f13, [%rd3+64];
	ld.volatile.shared.f32 	%f14, [%rd3];
	add.f32 	%f15, %f14, %f13;
	st.volatile.shared.f32 	[%rd3], %f15;
	ld.volatile.shared.f32 	%f16, [%rd3+32];
	ld.volatile.shared.f32 	%f17, [%rd3];
	add.f32 	%f18, %f17, %f16;
	st.volatile.shared.f32 	[%rd3], %f18;
	ld.volatile.shared.f32 	%f19, [%rd3+16];
	ld.volatile.shared.f32 	%f20, [%rd3];
	add.f32 	%f21, %f20, %f19;
	st.volatile.shared.f32 	[%rd3], %f21;
	ld.volatile.shared.f32 	%f22, [%rd3+8];
	ld.volatile.shared.f32 	%f23, [%rd3];
	add.f32 	%f24, %f23, %f22;
	st.volatile.shared.f32 	[%rd3], %f24;
	ld.volatile.shared.f32 	%f25, [%rd3+4];
	ld.volatile.shared.f32 	%f26, [%rd3];
	add.f32 	%f27, %f26, %f25;
	st.volatile.shared.f32 	[%rd3], %f27;

BB0_8:
	setp.ne.s32	%p7, %r2, 0;
	@%p7 bra 	BB0_10;

	cvta.to.global.u64 	%rd15, %rd4;
	ld.shared.f32 	%f28, [reducedot$__cuda_local_var_18290_35_non_const_sdata];
	atom.global.add.f32 	%f29, [%rd15], %f28;

BB0_10:
	ret;
}


`
)
