// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// k_regionadds_async dispatches the Metal implementation of cuda/regionadds.cu.
func k_regionadds_async(
	dst unsafe.Pointer,
	LUT unsafe.Pointer,
	regions unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("regionadds")
	}

	if dst == nil {
		panic("cuda/metal: kernel regionadds argument dst must not be nil")
	}
	if LUT == nil {
		panic("cuda/metal: kernel regionadds argument LUT must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel regionadds argument regions must not be nil")
	}

	var mumaxPointerMask uint32
	if dst != nil {
		mumaxPointerMask |= uint32(1) << 0
	}
	if LUT != nil {
		mumaxPointerMask |= uint32(1) << 1
	}
	if regions != nil {
		mumaxPointerMask |= uint32(1) << 2
	}

	metal.MustLaunch("regionadds", metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(LUT),
		metal.BufferArg(regions),
		metal.I32(N),
		metal.U32(mumaxPointerMask),
	)

	if Synchronous {
		Sync()
		timer.Stop("regionadds")
	}
}
