package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"unsafe"
)

var adduniaxialanisotropy_code cu.Function

type adduniaxialanisotropy_args struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_K1LUT   unsafe.Pointer
	arg_uxLUT   unsafe.Pointer
	arg_uyLUT   unsafe.Pointer
	arg_uzLUT   unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_N       int
	argptr      [12]unsafe.Pointer
}

// Wrapper for adduniaxialanisotropy CUDA kernel, asynchronous.
func k_adduniaxialanisotropy_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, K1LUT unsafe.Pointer, uxLUT unsafe.Pointer, uyLUT unsafe.Pointer, uzLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config, str cu.Stream) {
	if adduniaxialanisotropy_code == 0 {
		adduniaxialanisotropy_code = fatbinLoad(adduniaxialanisotropy_map, "adduniaxialanisotropy")
	}

	var a adduniaxialanisotropy_args

	a.arg_Bx = Bx
	a.argptr[0] = unsafe.Pointer(&a.arg_Bx)
	a.arg_By = By
	a.argptr[1] = unsafe.Pointer(&a.arg_By)
	a.arg_Bz = Bz
	a.argptr[2] = unsafe.Pointer(&a.arg_Bz)
	a.arg_mx = mx
	a.argptr[3] = unsafe.Pointer(&a.arg_mx)
	a.arg_my = my
	a.argptr[4] = unsafe.Pointer(&a.arg_my)
	a.arg_mz = mz
	a.argptr[5] = unsafe.Pointer(&a.arg_mz)
	a.arg_K1LUT = K1LUT
	a.argptr[6] = unsafe.Pointer(&a.arg_K1LUT)
	a.arg_uxLUT = uxLUT
	a.argptr[7] = unsafe.Pointer(&a.arg_uxLUT)
	a.arg_uyLUT = uyLUT
	a.argptr[8] = unsafe.Pointer(&a.arg_uyLUT)
	a.arg_uzLUT = uzLUT
	a.argptr[9] = unsafe.Pointer(&a.arg_uzLUT)
	a.arg_regions = regions
	a.argptr[10] = unsafe.Pointer(&a.arg_regions)
	a.arg_N = N
	a.argptr[11] = unsafe.Pointer(&a.arg_N)

	args := a.argptr[:]
	cu.LaunchKernel(adduniaxialanisotropy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, str, args)
}

// Wrapper for adduniaxialanisotropy CUDA kernel, synchronized.
func k_adduniaxialanisotropy(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, K1LUT unsafe.Pointer, uxLUT unsafe.Pointer, uyLUT unsafe.Pointer, uzLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	str := stream()
	k_adduniaxialanisotropy_async(Bx, By, Bz, mx, my, mz, K1LUT, uxLUT, uyLUT, uzLUT, regions, N, cfg, str)
	syncAndRecycle(str)
}

var adduniaxialanisotropy_map = map[int]string{0: "",
	20: adduniaxialanisotropy_ptx_20,
	30: adduniaxialanisotropy_ptx_30,
	35: adduniaxialanisotropy_ptx_35}

const (
	adduniaxialanisotropy_ptx_20 = `
.version 3.1
.target sm_20
.address_size 64


.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<2>;
	.reg .s32 	%r<23>;
	.reg .f32 	%f<19>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd20, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd13;
	cvta.to.global.u64 	%rd3, %rd12;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd16;
	cvta.to.global.u64 	%rd6, %rd15;
	cvta.to.global.u64 	%rd7, %rd18;
	cvta.to.global.u64 	%rd8, %rd19;
	cvta.to.global.u64 	%rd9, %rd20;
	.loc 2 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 2 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	.loc 2 14 1
	cvt.s64.s32 	%rd21, %r1;
	add.s64 	%rd22, %rd9, %rd21;
	.loc 2 15 1
	ld.global.s8 	%rd23, [%rd22];
	cvta.to.global.u64 	%rd24, %rd10;
	.loc 2 15 1
	shl.b64 	%rd25, %rd23, 2;
	add.s64 	%rd26, %rd24, %rd25;
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 2 16 1
	add.s64 	%rd28, %rd27, %rd25;
	.loc 2 17 1
	add.s64 	%rd29, %rd8, %rd25;
	.loc 2 19 1
	add.s64 	%rd30, %rd7, %rd25;
	.loc 2 20 1
	mul.wide.s32 	%rd31, %r1, 4;
	add.s64 	%rd32, %rd6, %rd31;
	add.s64 	%rd33, %rd5, %rd31;
	add.s64 	%rd34, %rd4, %rd31;
	.loc 2 19 1
	ld.global.f32 	%f1, [%rd30];
	.loc 2 21 1
	add.f32 	%f2, %f1, %f1;
	.loc 2 20 1
	ld.global.f32 	%f3, [%rd32];
	.loc 2 15 1
	ld.global.f32 	%f4, [%rd26];
	.loc 2 20 1
	ld.global.f32 	%f5, [%rd33];
	.loc 2 16 1
	ld.global.f32 	%f6, [%rd28];
	.loc 2 21 1
	mul.f32 	%f7, %f5, %f6;
	fma.rn.f32 	%f8, %f3, %f4, %f7;
	.loc 2 20 1
	ld.global.f32 	%f9, [%rd34];
	.loc 2 17 1
	ld.global.f32 	%f10, [%rd29];
	.loc 2 21 1
	fma.rn.f32 	%f11, %f9, %f10, %f8;
	mul.f32 	%f12, %f2, %f11;
	.loc 2 23 1
	add.s64 	%rd35, %rd3, %rd31;
	ld.global.f32 	%f13, [%rd35];
	fma.rn.f32 	%f14, %f12, %f4, %f13;
	st.global.f32 	[%rd35], %f14;
	.loc 2 24 1
	add.s64 	%rd36, %rd2, %rd31;
	ld.global.f32 	%f15, [%rd36];
	fma.rn.f32 	%f16, %f12, %f6, %f15;
	st.global.f32 	[%rd36], %f16;
	.loc 2 25 1
	add.s64 	%rd37, %rd1, %rd31;
	ld.global.f32 	%f17, [%rd37];
	fma.rn.f32 	%f18, %f12, %f10, %f17;
	st.global.f32 	[%rd37], %f18;

BB0_2:
	.loc 2 27 2
	ret;
}


`
	adduniaxialanisotropy_ptx_30 = `
.version 3.1
.target sm_30
.address_size 64


.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<2>;
	.reg .s32 	%r<23>;
	.reg .f32 	%f<19>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd20, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd13;
	cvta.to.global.u64 	%rd3, %rd12;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd16;
	cvta.to.global.u64 	%rd6, %rd15;
	cvta.to.global.u64 	%rd7, %rd18;
	cvta.to.global.u64 	%rd8, %rd19;
	cvta.to.global.u64 	%rd9, %rd20;
	.loc 2 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 2 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB0_2;

	.loc 2 14 1
	cvt.s64.s32 	%rd21, %r1;
	add.s64 	%rd22, %rd9, %rd21;
	.loc 2 15 1
	ld.global.s8 	%rd23, [%rd22];
	cvta.to.global.u64 	%rd24, %rd10;
	.loc 2 15 1
	shl.b64 	%rd25, %rd23, 2;
	add.s64 	%rd26, %rd24, %rd25;
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 2 16 1
	add.s64 	%rd28, %rd27, %rd25;
	.loc 2 17 1
	add.s64 	%rd29, %rd8, %rd25;
	.loc 2 19 1
	add.s64 	%rd30, %rd7, %rd25;
	.loc 2 20 1
	mul.wide.s32 	%rd31, %r1, 4;
	add.s64 	%rd32, %rd6, %rd31;
	add.s64 	%rd33, %rd5, %rd31;
	add.s64 	%rd34, %rd4, %rd31;
	.loc 2 19 1
	ld.global.f32 	%f1, [%rd30];
	.loc 2 21 1
	add.f32 	%f2, %f1, %f1;
	.loc 2 20 1
	ld.global.f32 	%f3, [%rd32];
	.loc 2 15 1
	ld.global.f32 	%f4, [%rd26];
	.loc 2 20 1
	ld.global.f32 	%f5, [%rd33];
	.loc 2 16 1
	ld.global.f32 	%f6, [%rd28];
	.loc 2 21 1
	mul.f32 	%f7, %f5, %f6;
	fma.rn.f32 	%f8, %f3, %f4, %f7;
	.loc 2 20 1
	ld.global.f32 	%f9, [%rd34];
	.loc 2 17 1
	ld.global.f32 	%f10, [%rd29];
	.loc 2 21 1
	fma.rn.f32 	%f11, %f9, %f10, %f8;
	mul.f32 	%f12, %f2, %f11;
	.loc 2 23 1
	add.s64 	%rd35, %rd3, %rd31;
	ld.global.f32 	%f13, [%rd35];
	fma.rn.f32 	%f14, %f12, %f4, %f13;
	st.global.f32 	[%rd35], %f14;
	.loc 2 24 1
	add.s64 	%rd36, %rd2, %rd31;
	ld.global.f32 	%f15, [%rd36];
	fma.rn.f32 	%f16, %f12, %f6, %f15;
	st.global.f32 	[%rd36], %f16;
	.loc 2 25 1
	add.s64 	%rd37, %rd1, %rd31;
	ld.global.f32 	%f17, [%rd37];
	fma.rn.f32 	%f18, %f12, %f10, %f17;
	st.global.f32 	[%rd37], %f18;

BB0_2:
	.loc 2 27 2
	ret;
}


`
	adduniaxialanisotropy_ptx_35 = `
.version 3.1
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 66 3
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 71 3
	ret;
}

.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<2>;
	.reg .s32 	%r<13>;
	.reg .f32 	%f<19>;
	.reg .s64 	%rd<38>;


	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd20, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd13;
	cvta.to.global.u64 	%rd3, %rd12;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd16;
	cvta.to.global.u64 	%rd6, %rd15;
	cvta.to.global.u64 	%rd7, %rd18;
	cvta.to.global.u64 	%rd8, %rd19;
	cvta.to.global.u64 	%rd9, %rd20;
	.loc 3 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 3 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB2_2;

	.loc 3 14 1
	cvt.s64.s32 	%rd21, %r1;
	add.s64 	%rd22, %rd9, %rd21;
	.loc 3 15 1
	ld.global.s8 	%rd23, [%rd22];
	cvta.to.global.u64 	%rd24, %rd10;
	.loc 3 15 1
	shl.b64 	%rd25, %rd23, 2;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.nc.f32 	%f1, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 3 16 1
	add.s64 	%rd28, %rd27, %rd25;
	ld.global.nc.f32 	%f2, [%rd28];
	.loc 3 17 1
	add.s64 	%rd29, %rd8, %rd25;
	ld.global.nc.f32 	%f3, [%rd29];
	.loc 3 19 1
	add.s64 	%rd30, %rd7, %rd25;
	ld.global.nc.f32 	%f4, [%rd30];
	.loc 3 20 1
	mul.wide.s32 	%rd31, %r1, 4;
	add.s64 	%rd32, %rd6, %rd31;
	ld.global.nc.f32 	%f5, [%rd32];
	add.s64 	%rd33, %rd5, %rd31;
	ld.global.nc.f32 	%f6, [%rd33];
	add.s64 	%rd34, %rd4, %rd31;
	ld.global.nc.f32 	%f7, [%rd34];
	.loc 3 21 1
	add.f32 	%f8, %f4, %f4;
	mul.f32 	%f9, %f6, %f2;
	fma.rn.f32 	%f10, %f5, %f1, %f9;
	fma.rn.f32 	%f11, %f7, %f3, %f10;
	mul.f32 	%f12, %f8, %f11;
	.loc 3 23 1
	add.s64 	%rd35, %rd3, %rd31;
	ld.global.nc.f32 	%f13, [%rd35];
	fma.rn.f32 	%f14, %f12, %f1, %f13;
	st.global.f32 	[%rd35], %f14;
	.loc 3 24 1
	add.s64 	%rd36, %rd2, %rd31;
	ld.global.nc.f32 	%f15, [%rd36];
	fma.rn.f32 	%f16, %f12, %f2, %f15;
	st.global.f32 	[%rd36], %f16;
	.loc 3 25 1
	add.s64 	%rd37, %rd1, %rd31;
	ld.global.nc.f32 	%f17, [%rd37];
	fma.rn.f32 	%f18, %f12, %f3, %f17;
	st.global.f32 	[%rd37], %f18;

BB2_2:
	.loc 3 27 2
	ret;
}


`
)
