package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/barnex/cuda5/cu"
	"unsafe"
)

var adduniaxialanisotropy_code cu.Function

type adduniaxialanisotropy_args struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_K1LUT   unsafe.Pointer
	arg_uxLUT   unsafe.Pointer
	arg_uyLUT   unsafe.Pointer
	arg_uzLUT   unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_N       int
	argptr      [12]unsafe.Pointer
}

// Wrapper for adduniaxialanisotropy CUDA kernel, asynchronous.
func k_adduniaxialanisotropy_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, K1LUT unsafe.Pointer, uxLUT unsafe.Pointer, uyLUT unsafe.Pointer, uzLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config, str cu.Stream) {
	if adduniaxialanisotropy_code == 0 {
		adduniaxialanisotropy_code = fatbinLoad(adduniaxialanisotropy_map, "adduniaxialanisotropy")
	}

	var _a_ adduniaxialanisotropy_args

	_a_.arg_Bx = Bx
	_a_.argptr[0] = unsafe.Pointer(&_a_.arg_Bx)
	_a_.arg_By = By
	_a_.argptr[1] = unsafe.Pointer(&_a_.arg_By)
	_a_.arg_Bz = Bz
	_a_.argptr[2] = unsafe.Pointer(&_a_.arg_Bz)
	_a_.arg_mx = mx
	_a_.argptr[3] = unsafe.Pointer(&_a_.arg_mx)
	_a_.arg_my = my
	_a_.argptr[4] = unsafe.Pointer(&_a_.arg_my)
	_a_.arg_mz = mz
	_a_.argptr[5] = unsafe.Pointer(&_a_.arg_mz)
	_a_.arg_K1LUT = K1LUT
	_a_.argptr[6] = unsafe.Pointer(&_a_.arg_K1LUT)
	_a_.arg_uxLUT = uxLUT
	_a_.argptr[7] = unsafe.Pointer(&_a_.arg_uxLUT)
	_a_.arg_uyLUT = uyLUT
	_a_.argptr[8] = unsafe.Pointer(&_a_.arg_uyLUT)
	_a_.arg_uzLUT = uzLUT
	_a_.argptr[9] = unsafe.Pointer(&_a_.arg_uzLUT)
	_a_.arg_regions = regions
	_a_.argptr[10] = unsafe.Pointer(&_a_.arg_regions)
	_a_.arg_N = N
	_a_.argptr[11] = unsafe.Pointer(&_a_.arg_N)

	args := _a_.argptr[:]
	cu.LaunchKernel(adduniaxialanisotropy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, str, args)
}

// Wrapper for adduniaxialanisotropy CUDA kernel, synchronized.
func k_adduniaxialanisotropy(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, K1LUT unsafe.Pointer, uxLUT unsafe.Pointer, uyLUT unsafe.Pointer, uzLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	str := stream()
	k_adduniaxialanisotropy_async(Bx, By, Bz, mx, my, mz, K1LUT, uxLUT, uyLUT, uzLUT, regions, N, cfg, str)
	syncAndRecycle(str)
}

var adduniaxialanisotropy_map = map[int]string{0: "",
	20: adduniaxialanisotropy_ptx_20,
	30: adduniaxialanisotropy_ptx_30,
	35: adduniaxialanisotropy_ptx_35}

const (
	adduniaxialanisotropy_ptx_20 = `
.version 3.1
.target sm_20
.address_size 64


.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<3>;
	.reg .s32 	%r<23>;
	.reg .f32 	%f<30>;
	.reg .s64 	%rd<39>;


	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd9, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd18;
	cvta.to.global.u64 	%rd6, %rd19;
	.loc 2 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 2 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB0_4;

	.loc 2 14 1
	cvt.s64.s32 	%rd7, %r1;
	add.s64 	%rd20, %rd6, %rd7;
	.loc 2 15 1
	ld.global.s8 	%rd8, [%rd20];
	cvta.to.global.u64 	%rd21, %rd12;
	.loc 2 15 1
	shl.b64 	%rd22, %rd8, 2;
	add.s64 	%rd23, %rd21, %rd22;
	cvta.to.global.u64 	%rd24, %rd13;
	.loc 2 16 1
	add.s64 	%rd25, %rd24, %rd22;
	.loc 2 17 1
	add.s64 	%rd26, %rd5, %rd22;
	.loc 2 15 1
	ld.global.f32 	%f1, [%rd23];
	.loc 2 16 1
	ld.global.f32 	%f2, [%rd25];
	.loc 2 18 1
	mul.f32 	%f8, %f2, %f2;
	fma.rn.f32 	%f9, %f1, %f1, %f8;
	.loc 2 17 1
	ld.global.f32 	%f3, [%rd26];
	.loc 2 18 1
	fma.rn.f32 	%f10, %f3, %f3, %f9;
	.loc 3 991 5
	sqrt.rn.f32 	%f4, %f10;
	mov.f32 	%f29, 0f00000000;
	.loc 2 18 1
	setp.eq.f32 	%p2, %f4, 0f00000000;
	@%p2 bra 	BB0_3;

	rcp.rn.f32 	%f29, %f4;

BB0_3:
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 2 19 1
	add.s64 	%rd29, %rd27, %rd22;
	cvta.to.global.u64 	%rd30, %rd9;
	.loc 2 20 1
	shl.b64 	%rd31, %rd7, 2;
	add.s64 	%rd32, %rd30, %rd31;
	cvta.to.global.u64 	%rd33, %rd10;
	.loc 2 20 1
	add.s64 	%rd34, %rd33, %rd31;
	.loc 2 19 1
	ld.global.f32 	%f11, [%rd29];
	.loc 2 21 1
	add.f32 	%f12, %f11, %f11;
	.loc 2 20 1
	ld.global.f32 	%f13, [%rd32];
	.loc 2 18 1
	mul.f32 	%f14, %f29, %f1;
	.loc 2 20 1
	ld.global.f32 	%f15, [%rd34];
	.loc 2 18 1
	mul.f32 	%f16, %f29, %f2;
	.loc 2 21 1
	mul.f32 	%f17, %f15, %f16;
	fma.rn.f32 	%f18, %f13, %f14, %f17;
	.loc 2 20 1
	add.s64 	%rd35, %rd4, %rd31;
	ld.global.f32 	%f19, [%rd35];
	.loc 2 18 1
	mul.f32 	%f20, %f29, %f3;
	.loc 2 21 1
	fma.rn.f32 	%f21, %f19, %f20, %f18;
	mul.f32 	%f22, %f12, %f21;
	.loc 2 23 1
	add.s64 	%rd36, %rd3, %rd31;
	ld.global.f32 	%f23, [%rd36];
	fma.rn.f32 	%f24, %f22, %f14, %f23;
	st.global.f32 	[%rd36], %f24;
	.loc 2 24 1
	add.s64 	%rd37, %rd2, %rd31;
	ld.global.f32 	%f25, [%rd37];
	fma.rn.f32 	%f26, %f22, %f16, %f25;
	st.global.f32 	[%rd37], %f26;
	.loc 2 25 1
	add.s64 	%rd38, %rd1, %rd31;
	ld.global.f32 	%f27, [%rd38];
	fma.rn.f32 	%f28, %f22, %f20, %f27;
	st.global.f32 	[%rd38], %f28;

BB0_4:
	.loc 2 27 2
	ret;
}


`
	adduniaxialanisotropy_ptx_30 = `
.version 3.1
.target sm_30
.address_size 64


.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<3>;
	.reg .s32 	%r<23>;
	.reg .f32 	%f<30>;
	.reg .s64 	%rd<39>;


	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd9, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd18;
	cvta.to.global.u64 	%rd6, %rd19;
	.loc 2 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 2 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB0_4;

	.loc 2 14 1
	cvt.s64.s32 	%rd7, %r1;
	add.s64 	%rd20, %rd6, %rd7;
	.loc 2 15 1
	ld.global.s8 	%rd8, [%rd20];
	cvta.to.global.u64 	%rd21, %rd12;
	.loc 2 15 1
	shl.b64 	%rd22, %rd8, 2;
	add.s64 	%rd23, %rd21, %rd22;
	cvta.to.global.u64 	%rd24, %rd13;
	.loc 2 16 1
	add.s64 	%rd25, %rd24, %rd22;
	.loc 2 17 1
	add.s64 	%rd26, %rd5, %rd22;
	.loc 2 15 1
	ld.global.f32 	%f1, [%rd23];
	.loc 2 16 1
	ld.global.f32 	%f2, [%rd25];
	.loc 2 18 1
	mul.f32 	%f8, %f2, %f2;
	fma.rn.f32 	%f9, %f1, %f1, %f8;
	.loc 2 17 1
	ld.global.f32 	%f3, [%rd26];
	.loc 2 18 1
	fma.rn.f32 	%f10, %f3, %f3, %f9;
	.loc 3 991 5
	sqrt.rn.f32 	%f4, %f10;
	mov.f32 	%f29, 0f00000000;
	.loc 2 18 1
	setp.eq.f32 	%p2, %f4, 0f00000000;
	@%p2 bra 	BB0_3;

	rcp.rn.f32 	%f29, %f4;

BB0_3:
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 2 19 1
	add.s64 	%rd29, %rd27, %rd22;
	cvta.to.global.u64 	%rd30, %rd9;
	.loc 2 20 1
	shl.b64 	%rd31, %rd7, 2;
	add.s64 	%rd32, %rd30, %rd31;
	cvta.to.global.u64 	%rd33, %rd10;
	.loc 2 20 1
	add.s64 	%rd34, %rd33, %rd31;
	.loc 2 19 1
	ld.global.f32 	%f11, [%rd29];
	.loc 2 21 1
	add.f32 	%f12, %f11, %f11;
	.loc 2 20 1
	ld.global.f32 	%f13, [%rd32];
	.loc 2 18 1
	mul.f32 	%f14, %f29, %f1;
	.loc 2 20 1
	ld.global.f32 	%f15, [%rd34];
	.loc 2 18 1
	mul.f32 	%f16, %f29, %f2;
	.loc 2 21 1
	mul.f32 	%f17, %f15, %f16;
	fma.rn.f32 	%f18, %f13, %f14, %f17;
	.loc 2 20 1
	add.s64 	%rd35, %rd4, %rd31;
	ld.global.f32 	%f19, [%rd35];
	.loc 2 18 1
	mul.f32 	%f20, %f29, %f3;
	.loc 2 21 1
	fma.rn.f32 	%f21, %f19, %f20, %f18;
	mul.f32 	%f22, %f12, %f21;
	.loc 2 23 1
	add.s64 	%rd36, %rd3, %rd31;
	ld.global.f32 	%f23, [%rd36];
	fma.rn.f32 	%f24, %f22, %f14, %f23;
	st.global.f32 	[%rd36], %f24;
	.loc 2 24 1
	add.s64 	%rd37, %rd2, %rd31;
	ld.global.f32 	%f25, [%rd37];
	fma.rn.f32 	%f26, %f22, %f16, %f25;
	st.global.f32 	[%rd37], %f26;
	.loc 2 25 1
	add.s64 	%rd38, %rd1, %rd31;
	ld.global.f32 	%f27, [%rd38];
	fma.rn.f32 	%f28, %f22, %f20, %f27;
	st.global.f32 	[%rd38], %f28;

BB0_4:
	.loc 2 27 2
	ret;
}


`
	adduniaxialanisotropy_ptx_35 = `
.version 3.1
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 66 3
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	.loc 2 71 3
	ret;
}

.visible .entry adduniaxialanisotropy(
	.param .u64 adduniaxialanisotropy_param_0,
	.param .u64 adduniaxialanisotropy_param_1,
	.param .u64 adduniaxialanisotropy_param_2,
	.param .u64 adduniaxialanisotropy_param_3,
	.param .u64 adduniaxialanisotropy_param_4,
	.param .u64 adduniaxialanisotropy_param_5,
	.param .u64 adduniaxialanisotropy_param_6,
	.param .u64 adduniaxialanisotropy_param_7,
	.param .u64 adduniaxialanisotropy_param_8,
	.param .u64 adduniaxialanisotropy_param_9,
	.param .u64 adduniaxialanisotropy_param_10,
	.param .u32 adduniaxialanisotropy_param_11
)
{
	.reg .pred 	%p<3>;
	.reg .s32 	%r<13>;
	.reg .f32 	%f<30>;
	.reg .s64 	%rd<39>;


	ld.param.u64 	%rd14, [adduniaxialanisotropy_param_0];
	ld.param.u64 	%rd15, [adduniaxialanisotropy_param_1];
	ld.param.u64 	%rd16, [adduniaxialanisotropy_param_2];
	ld.param.u64 	%rd9, [adduniaxialanisotropy_param_3];
	ld.param.u64 	%rd10, [adduniaxialanisotropy_param_4];
	ld.param.u64 	%rd17, [adduniaxialanisotropy_param_5];
	ld.param.u64 	%rd11, [adduniaxialanisotropy_param_6];
	ld.param.u64 	%rd12, [adduniaxialanisotropy_param_7];
	ld.param.u64 	%rd13, [adduniaxialanisotropy_param_8];
	ld.param.u64 	%rd18, [adduniaxialanisotropy_param_9];
	ld.param.u64 	%rd19, [adduniaxialanisotropy_param_10];
	ld.param.u32 	%r2, [adduniaxialanisotropy_param_11];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd15;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd17;
	cvta.to.global.u64 	%rd5, %rd18;
	cvta.to.global.u64 	%rd6, %rd19;
	.loc 3 11 1
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	.loc 3 12 1
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	BB2_4;

	.loc 3 14 1
	cvt.s64.s32 	%rd7, %r1;
	add.s64 	%rd20, %rd6, %rd7;
	.loc 3 15 1
	ld.global.s8 	%rd8, [%rd20];
	cvta.to.global.u64 	%rd21, %rd12;
	.loc 3 15 1
	shl.b64 	%rd22, %rd8, 2;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.nc.f32 	%f1, [%rd23];
	cvta.to.global.u64 	%rd24, %rd13;
	.loc 3 16 1
	add.s64 	%rd25, %rd24, %rd22;
	ld.global.nc.f32 	%f2, [%rd25];
	.loc 3 17 1
	add.s64 	%rd26, %rd5, %rd22;
	ld.global.nc.f32 	%f3, [%rd26];
	.loc 3 18 1
	mul.f32 	%f8, %f2, %f2;
	fma.rn.f32 	%f9, %f1, %f1, %f8;
	fma.rn.f32 	%f10, %f3, %f3, %f9;
	.loc 4 991 5
	sqrt.rn.f32 	%f4, %f10;
	mov.f32 	%f29, 0f00000000;
	.loc 3 18 1
	setp.eq.f32 	%p2, %f4, 0f00000000;
	@%p2 bra 	BB2_3;

	rcp.rn.f32 	%f29, %f4;

BB2_3:
	cvta.to.global.u64 	%rd27, %rd11;
	.loc 3 19 1
	add.s64 	%rd29, %rd27, %rd22;
	ld.global.nc.f32 	%f11, [%rd29];
	cvta.to.global.u64 	%rd30, %rd9;
	.loc 3 20 1
	shl.b64 	%rd31, %rd7, 2;
	add.s64 	%rd32, %rd30, %rd31;
	ld.global.nc.f32 	%f12, [%rd32];
	cvta.to.global.u64 	%rd33, %rd10;
	.loc 3 20 1
	add.s64 	%rd34, %rd33, %rd31;
	ld.global.nc.f32 	%f13, [%rd34];
	add.s64 	%rd35, %rd4, %rd31;
	ld.global.nc.f32 	%f14, [%rd35];
	.loc 3 21 1
	add.f32 	%f15, %f11, %f11;
	.loc 3 18 1
	mul.f32 	%f16, %f29, %f1;
	mul.f32 	%f17, %f29, %f2;
	.loc 3 21 1
	mul.f32 	%f18, %f13, %f17;
	fma.rn.f32 	%f19, %f12, %f16, %f18;
	.loc 3 18 1
	mul.f32 	%f20, %f29, %f3;
	.loc 3 21 1
	fma.rn.f32 	%f21, %f14, %f20, %f19;
	mul.f32 	%f22, %f15, %f21;
	.loc 3 23 1
	add.s64 	%rd36, %rd3, %rd31;
	ld.global.nc.f32 	%f23, [%rd36];
	fma.rn.f32 	%f24, %f22, %f16, %f23;
	st.global.f32 	[%rd36], %f24;
	.loc 3 24 1
	add.s64 	%rd37, %rd2, %rd31;
	ld.global.nc.f32 	%f25, [%rd37];
	fma.rn.f32 	%f26, %f22, %f17, %f25;
	st.global.f32 	[%rd37], %f26;
	.loc 3 25 1
	add.s64 	%rd38, %rd1, %rd31;
	ld.global.nc.f32 	%f27, [%rd38];
	fma.rn.f32 	%f28, %f22, %f20, %f27;
	st.global.f32 	[%rd38], %f28;

BB2_4:
	.loc 3 27 2
	ret;
}


`
)
